import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
import {diagnoseComplaint} from '../../js/complaints.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS '+name);};
function setup(){const sim=makeMaple(27);sim.s.tut.done=true;sim.s.tut.on=false;const u=sim.objs('unit')[0];return {sim,u,ag:{id:999,kind:'cust',x:u.x,y:u.y,f:0,size:u.size}};}
test('full inventory shows capacity remedy with original lost-demand accounting',()=>{const {sim,u,ag}=setup();for(const u of sim.objs('unit'))u.commercial='occupied';const cash=sim.s.cash;sim.decideLease({size:u.size,climate:false},ag);const th=sim.s.thoughts.at(-1);assert.equal(th.text,'All units occupied or reserved.');assert.equal(th.availability,'full');assert.equal(sim.s.lost.noReady,1);assert.equal(sim.s.cash,cash);assert.match(diagnoseComplaint(sim,th).remedy,/Growth Readiness/);});
for(const [reason,changes,pattern] of [['makeReady',{commercial:'unready',lease:null},/make-ready/],['access',{commercial:'ready',lease:null,blocked:true},/reconnect/],['construction',{commercial:'ready',lease:null,cstate:'construction'},/commissioning/]])test(reason+' report has distinct cause and remedy',()=>{const {sim,u}=setup();for(const x of sim.objs('unit'))x.commercial='occupied';Object.assign(u,changes);const r=sim.availabilityReport(u.size),th={...r,kind:'bad',requestedSize:u.size};assert.equal(r.availability,reason);assert.match(diagnoseComplaint(sim,th).remedy,pattern);});
test('historical availability diagnosis survives reload and later vacancy',()=>{const {sim,u,ag}=setup();for(const x of sim.objs('unit'))x.commercial='occupied';sim.decideLease({size:u.size,climate:false},ag);const saved=new Sim(JSON.parse(JSON.stringify(sim.s)));saved.s.objects[u.id].commercial='unready';assert.match(diagnoseComplaint(saved,saved.s.thoughts.at(-1)).cause,/were occupied or reserved/);});
function bubbleUI(sim){const ui=Object.create(UI.prototype);ui.g={sim};ui.feedbackSim=sim;ui.bubbles=[];ui.bubbleSeen=new Map();ui.phone=()=>true;ui.bindComplaintBubble=()=>{};ui.bubRoot={appendChild(){}};return ui;}
globalThis.document={createElement(){return {innerHTML:'',remove(){}};}};
test('identical visible availability bubbles collapse across different requested sizes',()=>{const {sim}=setup(),ui=bubbleUI(sim);const a={text:'All units occupied or reserved.',complaint:'noReady',availability:'full',kind:'bad',requestedSize:'5x5'},b={...a,requestedSize:'10x20'};ui.addBubble(a);ui.addBubble(b);assert.equal(ui.bubbles.length,1);assert.match(ui.bubbles[0].el.innerHTML,/×2/);assert.equal(ui.bubbles[0].th.requestedSize,'5x5');});
test('legacy identical availability text also collapses without losing history keys',()=>{const {sim}=setup(),ui=bubbleUI(sim);ui.addBubble({text:'Nothing ready to rent today.',kind:'bad',requestedSize:'5x5'});ui.addBubble({text:'Nothing ready to rent today.',kind:'bad',requestedSize:'10x20'});assert.equal(ui.bubbles.length,1);});
test('distinct local faults remain distinct visual reports',()=>{const {sim,u}=setup(),ui=bubbleUI(sim);ui.addBubble({text:'The hallway is dark.',kind:'bad',location:{obj:u.id}});ui.addBubble({text:'The hallway is dark.',kind:'bad',location:{obj:u.id+1}});assert.equal(ui.bubbles.length,2);});
console.log(`${n} availability checks passed`);
