import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
import {diagnoseComplaint,complaintKey} from '../../js/complaints.js';
let now=10000;globalThis.performance={now:()=>now};globalThis.document={createElement(){return {innerHTML:'',removed:false,remove(){this.removed=true;}};}};
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS '+name);};
function fixture(){const sim=makeMaple(29);sim.s.tut.done=true;sim.s.tut.on=false;sim.s.speed=4;
 const ui=Object.create(UI.prototype);ui.g={sim,rend:{pool:{ppl:new Map()},project:()=>({x:100,y:100})}};ui.feedbackSim=sim;ui.bubbles=[];ui.toasts=[];ui.bubbleSeen=new Map();ui.phone=()=>true;ui.bubRoot={appendChild(){}};ui.bindComplaintBubble=(el,th)=>{el.report=th;};return {sim,ui};}
function th(size='5x5',extra={}){return {text:'I need climate control.',kind:'bad',complaint:'noClimate',requestedSize:size,requestedClimate:true,location:{x:2,y:3,f:0},...extra};}
test('identical climate text merges across requested sizes',()=>{const {ui}=fixture();ui.addBubble(th());ui.addBubble(th('10x20'));assert.equal(ui.bubbles.length,1);assert.match(ui.bubbles[0].el.innerHTML,/×2/);});
test('merged bubble retains original report and usable climate remedy',()=>{const {sim,ui}=fixture();const a=th('5x5'),b=th('10x20',{location:{x:12,y:9,f:0}});ui.addBubble(a);ui.addBubble(b);assert.equal(ui.bubbles[0].el.report,a);assert.equal(ui.bubbles[0].th,a);assert.match(diagnoseComplaint(sim,a).remedy,/climate/);assert.notEqual(complaintKey(a),complaintKey(b));});
test('4x demand bursts keep each product, historical location and economic count',()=>{const {sim,ui}=fixture();for(const u of sim.objs('unit'))u.commercial='occupied';const sizes=[...new Set(sim.objs('unit').map(u=>u.size))].slice(0,2);assert.equal(sizes.length,2);const cash=sim.s.cash,control=new Sim(JSON.parse(JSON.stringify(sim.s)));
 for(let i=0;i<8;i++){const size=sizes[i%2],ag={id:900+i,kind:'cust',size,x:2+i,y:3,f:0};sim.s.t+=25;control.s.t+=25;control.decideLease({size,climate:true},{...ag});const start=sim.events.length;sim.decideLease({size,climate:true},ag);for(const e of sim.events.slice(start))if(e.type==='thought')ui.addBubble(e);}
 assert.equal(ui.bubbles.length,1);assert.match(ui.bubbles[0].el.innerHTML,/×8/);assert.equal(sim.s.lost.noClimate,8);assert.equal(sim.s.today.lost,8);assert.equal(sim.s.cash,cash);assert.equal(sim.s.thoughts.filter(t=>t.complaint==='noClimate').length,8);assert.equal(new Set(sim.s.thoughts.map(t=>t.requestedSize)).size,2);assert.equal(new Set(sim.s.thoughts.map(t=>t.ag)).size,8);assert.ok(sim.s.thoughts.every(t=>t.location.obj===sim.objs('office')[0].id));
 assert.deepEqual(sim.s,control.s);const before=JSON.stringify(sim.s);const html=ui.feedbackSheet();assert.match(html,/Requested 5x/);assert.match(html,/Why then:/);assert.match(html,/Next:/);assert.match(html,/Report context/);assert.match(html,/View reported location/);assert.equal(JSON.stringify(sim.s),before);
});
test('legacy climate reports merge with modern reports',()=>{const {ui}=fixture();ui.addBubble(th('5x5',{complaint:undefined}));ui.addBubble(th('10x20'));assert.equal(ui.bubbles.length,1);});
test('different complaint text and local fault targets remain separate',()=>{const {ui}=fixture();ui.addBubble(th());ui.addBubble({text:'The hallway is dark.',kind:'bad',location:{obj:1}});assert.equal(ui.bubbles.length,2);const {ui:local}=fixture();local.addBubble({text:'The hallway is dark.',kind:'bad',location:{obj:1}});local.addBubble({text:'The hallway is dark.',kind:'bad',location:{obj:2}});assert.equal(local.bubbles.length,2);});
test('distinct recorded climate causes are not collapsed',()=>{const {ui}=fixture();ui.addBubble(th('5x5',{availability:'full'}));ui.addBubble(th('10x20',{availability:'construction'}));assert.equal(ui.bubbles.length,2);});
test('different severity remains separate',()=>{const {ui}=fixture();ui.addBubble(th());ui.addBubble(th('10x20',{kind:'neutral'}));assert.equal(ui.bubbles.length,2);});
test('repeated arrivals never extend original bubble lifetime',()=>{const {ui}=fixture();now=10000;ui.addBubble(th());const original=ui.bubbles[0];now=14000;ui.addBubble(th('10x20'));assert.equal(original.t,10000);now=14600;ui.updateBubbles();assert.equal(ui.bubbles.length,0);assert.equal(original.el.removed,true);});
test('dismissed routine text respects cooldown then returns',()=>{const {ui}=fixture();now=10000;ui.addBubble(th());now=14600;ui.updateBubbles();ui.addBubble(th('10x20'));assert.equal(ui.bubbles.length,0);now=22100;ui.addBubble(th('10x20'));assert.equal(ui.bubbles.length,1);});
test('save reload preserves detailed climate reports and resets visual cooldown',()=>{const {sim,ui}=fixture();sim.thought({id:901,kind:'cust',size:'5x5',x:3,y:4,f:0},'I need climate control.','bad',{requestedClimate:true});sim.thought({id:902,kind:'cust',size:'10x20',x:8,y:9,f:0},'I need climate control.','bad',{requestedClimate:true});for(const t of sim.s.thoughts)ui.addBubble(t);const old=ui.bubbles[0].el;
 const loaded=new Sim(JSON.parse(JSON.stringify(sim.s)));ui.g.sim=loaded;ui.syncFeedbackProperty();assert.equal(old.removed,true);assert.equal(ui.bubbleSeen.size,0);assert.equal(ui.bubbles.length,0);for(const t of loaded.s.thoughts)ui.addBubble(t);assert.equal(ui.bubbles.length,1);assert.equal(loaded.s.thoughts.length,2);assert.equal(loaded.s.thoughts[0].requestedSize,'5x5');assert.equal(loaded.s.thoughts[1].requestedSize,'10x20');assert.match(ui.feedbackSheet(),/Requested 10x20/);});
console.log(`${n} climate bubble checks passed`);
