// Real production methods with explicit threshold/capital fixtures; no device acceptance implied.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {Sim,fmtTime} from '../../js/sim.js';
import {makeScenario,makeSandbox,SCENARIOS,modeLabel,sandboxName} from '../../js/scenarios.js';
import {makeMaple} from '../../js/maple.js';
import {MARKETS,ROLES,MIN_PER_DAY,FLOOR_H,TIERS} from '../../js/data.js';
import {FINANCIAL_MINUTE} from '../../js/finance.js';
import {installTutorial,lessonTick,lessonAllowed,lessonById} from '../../js/tutorial.js';
import {careerEligibility,portfolioCareer} from '../../js/career.js';
import {UI} from '../../js/ui.js';
import {localsave} from '../../js/localsave.js';
import {savearchive} from '../../js/savearchive.js';
const main=readFileSync('js/main.js','utf8');
const ctx=vm.createContext({portfolioCareer,Sim,fmtTime,makeScenario,makeSandbox,makeMaple,SCENARIOS,modeLabel,sandboxName,MARKETS,ROLES,MIN_PER_DAY,FLOOR_H,TIERS,FINANCIAL_MINUTE,installTutorial,localsave,savearchive,Audio:class{},performance,console,BUILD:{name:'career37-test'},cloud:{ok:false},CompressionStream,DecompressionStream,Response,Blob,btoa,atob,escape,unescape,encodeURIComponent,decodeURIComponent});
vm.runInContext(main.slice(main.indexOf('const game = {'),main.indexOf('// initial world'))+main.slice(main.indexOf('const WORKING_FLOAT'),main.indexOf('// Save codes'))+main.slice(main.indexOf('function validState('),main.indexOf('function makeMapleSeedPrice'))+'function makeMapleSeedPrice(day){return 95000+(day%7)*1500;}globalThis.game=game;',ctx);
const g=ctx.game;g.attach=function(sim){this.sim=sim;installTutorial(sim)};g.ui={title:false,setMeta(){},renderFeed(){},toast(){}};g.drain=()=>{};
vm.runInContext(main.slice(main.indexOf('const BG_EVENTS'),main.indexOf('let last = performance.now'))+'globalThis.stepTicks=stepTicks;',ctx);
let n=0;async function test(name,fn){await fn();n++;console.log('PASS '+name)}
const fresh=()=>makeScenario('comeback');
function won(){const sm=fresh();for(const t of sm.s.scenario.targets){const tk=sm.s.tasks.find(x=>x.obj===t.id);sm.finishTask(tk,sm.s.agents.find(a=>a.role==='owner'));sm.poll();}assert.equal(sm.s.scenario.status,'won');return sm;}
function ordinary(){return makeSandbox({start:'starter',cash:60000});}
function company(props,active=0){g.company={props:props.map((sim,i)=>({name:'P'+i,sim})),active,feed:[]};g.sim=props[active];}
function roll(sm,value){const factor=value/sm.rentRoll();for(const L of Object.values(sm.s.leases))L.rent*=factor;}
await test('eligibility matrix and pure reads',()=>{const W=won();const cases=[[fresh(),false],[W,false],[ordinary(),true],[makeMaple(),false],[makeScenario('turnaround'),false],[makeScenario('vertical'),false],[makeScenario('climate'),false],[makeSandbox({kind:'free'}),true]];W.dispatch({type:'comebackAck'});cases.push([W,true]);for(const [sm,expected]of cases){if(sm===W&&expected===false)continue;const before=JSON.stringify(sm.s);assert.equal(careerEligibility(sm.s).eligible,expected);assert.equal(JSON.stringify(sm.s),before);}const M=makeMaple();M.s.tut.done=true;assert.equal(careerEligibility(M.s).eligible,true);M.s.creative=true;assert.equal(careerEligibility(M.s).eligible,false);});
await test('unacknowledged win excluded and acknowledgement changes only acknowledgement',()=>{const sm=won(),before=structuredClone(sm.s);assert.equal(careerEligibility(sm.s).eligible,false);assert.ok(sm.dispatch({type:'comebackAck'}).ok);before.scenario.acknowledged=true;assert.deepEqual(sm.s,before);assert.equal(careerEligibility(sm.s).eligible,true);});
await test('historical win survives deterioration, deletion and reload',()=>{const sm=won();sm.dispatch({type:'comebackAck'});sm.s.objects[sm.s.scenario.targets[0].id].blocked=true;delete sm.s.objects[sm.s.scenario.targets[1].id];sm.markDirty();sm.rebuild();const loaded=new Sim(structuredClone(sm.s));assert.equal(careerEligibility(loaded.s).eligible,true);assert.deepEqual(loaded.s.scenario.earned,[true,true,true]);});
await test('malformed completion is excluded and normalized safely',()=>{const sm=won();sm.dispatch({type:'comebackAck'});sm.s.scenario.targets[0].x=-1;assert.equal(careerEligibility(sm.s).eligible,false);const loaded=new Sim(structuredClone(sm.s));assert.equal(loaded.s.scenario.status,'unavailable');assert.equal(careerEligibility(loaded.s).eligible,false);});
await test('empty eligible portfolio cannot promote',()=>{company([fresh()]);g.syncTier();assert.equal(g.tierInfo().cur,null);assert.equal(g.sim.s.coTier,1);});
await test('all five thresholds and eligible property counts',()=>{for(const T of TIERS){const props=Array.from({length:T.props},ordinary);for(const sm of props)roll(sm,T.roll/props.length);let info=portfolioCareer(props.map(sim=>({sim})));assert.equal(info.qualified.n,T.n);assert.equal(info.cur.n,1);assert.equal(info.target.n,T.n);if(T.n>1){roll(props[0],Math.max(0,T.roll/props.length-.01));info=portfolioCareer(props.map(sim=>({sim})));assert.ok(info.qualified.n<T.n);}}});
await test('selected active scenario cannot block or receive normal-property promotion',()=>{for(const active of [0,1]){const A=fresh(),B=ordinary();roll(A,100000);roll(B,4375);company([A,B],active);g.syncTier();assert.equal(A.s.coTier,1);assert.equal(B.s.coTier,2);assert.equal(g.tierInfo().n,1);assert.equal(g.tierInfo().roll,4375);}});
await test('excluded legacy tier cannot propagate; stored tier is preserved',()=>{const A=fresh(),B=ordinary();A.s.coTier=5;roll(B,1000);company([A,B]);g.syncTier();assert.equal(A.s.coTier,5);assert.equal(B.s.coTier,1);});
await test('earned tier persists and eligible acquired property inherits it once',()=>{const A=won(),B=ordinary();A.dispatch({type:'comebackAck'});A.s.coTier=3;roll(A,1000);roll(B,1000);company([A,B]);g.syncTier();assert.equal(g.tierInfo().cur.n,3);assert.equal(g.tierInfo().qualified.n,1);assert.equal(B.s.coTier,3);const count=B.events.filter(e=>e.type==='tier_up').length;g.syncTier();assert.equal(B.events.filter(e=>e.type==='tier_up').length,count);});
await test('complete company hour snapshot is selection independent',()=>{for(const active of [0,1]){const props=[0,1].map((_,i)=>({s:{t:59,speed:1,convos:[],coTier:1,mode:'sandbox'},events:[],rentRoll(){return this.s.t>=60&&i===1?8750:0},step(){this.s.t++},dispatch(a){this.s.coTier=a.tier}}));company(props,active);ctx.stepTicks(1);assert.equal(props[0].s.coTier,3);assert.equal(props[1].s.coTier,3);assert.deepEqual(props.map(p=>p.s.t),[60,60]);}});
await test('generic lessons allowed only after handoff, Maple lessons still excluded',()=>{const sm=won();assert.equal(sm.dispatch({type:'lesson',op:'start',id:'financing'}).ok,false);sm.dispatch({type:'comebackAck'});for(const id of ['collections','financing'])assert.equal(lessonAllowed(sm,lessonById(id)),true);for(const id of ['up','climate','interior','quality','missing'])assert.equal(sm.dispatch({type:'lesson',op:'start',id}).ok,false);assert.ok(sm.dispatch({type:'lesson',op:'start',id:'financing'}).ok);lessonTick(sm);assert.equal(sm.s.lesson.entered,true);});
await test('sandbox tier overrides and options untouched',()=>{const sm=makeSandbox({kind:'free',tiers:'all',instant:true});const before=structuredClone(sm.s.sb);company([sm]);g.syncTier();assert.deepEqual(sm.s.sb,before);assert.equal(sm.s.coTier,4);});
await test('acquisition and transfers preserve books and clock',()=>{const A=won();A.dispatch({type:'comebackAck'});A.s.cash=150000;company([A]);const offer=g.offers().find(o=>o.kind==='facility');assert.ok(g.acquire('facility','maple').ok);const B=g.company.props[1].sim;assert.equal(A.s.cash,150000-offer.price);assert.equal(B.s.cash,5000);assert.equal(A.s.t,B.s.t);assert.equal(careerEligibility(B.s).eligible,true);const total=A.s.cash+B.s.cash;assert.ok(g.transfer(0,1,10000).ok);assert.equal(A.s.cash+B.s.cash,total);});
await test('raw and compressed portfolio saves preserve complete state without load-time promotion',async()=>{g.company.props[0].sim.s.coTier=3;g.company.props[1].sim.s.coTier=1;for(const code of [g.rawSaveCode(g.saveJSON()),await g.saveCode()]){const before=g.saveJSON(),prep=await g.prepareLoad(code);assert.ok(prep.ok);assert.equal(g.saveJSON(),before);assert.ok(g.applyLoad(prep));assert.equal(g.saveJSON(),before);assert.equal(g.company.props[1].sim.s.coTier,1);}});
await test('completion markup and navigation reuse existing sections without spending',()=>{const sm=won();sm.dispatch({type:'comebackAck'});const box={innerHTML:'',querySelector(){return null}},u=Object.create(UI.prototype);u.g={sim:sm,rend:{setFocus(){}},audio:{unlock(){},play(){}}};u.$=()=>box;u.scMin=true;u.title=false;u.toasts=[];u.renderComeback(true);assert.match(box.innerHTML,/Rescue history/);assert.match(box.innerHTML,/comebackReadiness/);assert.match(box.innerHTML,/comebackCareer/);const calls=[],before=JSON.stringify(sm.s);u.renderTut=()=>{};u.select=()=>{};u.setTab=t=>calls.push(t);u.jumpSection=t=>calls.push(t);for(const a of ['comebackReadiness','comebackCareer'])u.onClick({target:{closest(){return {dataset:{a},closest(){return null}}}}});assert.deepEqual(calls,['growth','Growth Readiness','growth','Operator career']);assert.equal(JSON.stringify(sm.s),before);});
await test('career markup shows earned perks after roll falls, excludes active challenge card',()=>{const A=won();A.dispatch({type:'comebackAck'});A.s.coTier=3;roll(A,1000);const B=fresh();company([A,B]);const u=Object.create(UI.prototype);u.g=g;u.sheet=(title,sub,h)=>h;u.diagnosticHtml=()=>'';u.portfolioHtml=()=>'';const html=u.growthSheet();assert.match(html,/Regional operator/);assert.match(html,/Career rent roll/);assert.match(html,/Career participation/);assert.match(html,/collections/);g.sim=B;const excluded=u.growthSheet();assert.doesNotMatch(excluded,/<h3>Operator career/);assert.doesNotMatch(excluded,/<h3>Lessons/);});
await test('stale Maple-only lesson cannot tick on completed Comeback',()=>{const A=won();A.dispatch({type:'comebackAck'});A.s.lesson={id:'up',entered:false,built:[],flags:{},idMark:A.s.nextId};const before=JSON.stringify(A.s);lessonTick(A);assert.equal(JSON.stringify(A.s),before);});
await test('generic lesson renders instead of rescue panel and returns to history',()=>{const A=won();A.dispatch({type:'comebackAck'});A.dispatch({type:'lesson',op:'start',id:'financing'});const box={innerHTML:'',querySelector(){return null}},u=Object.create(UI.prototype);u.g={sim:A,rend:{setFocus(){}}};u.$=()=>box;u.title=false;u.tutMin=false;u.scMin=true;u.toasts=[];u.phone=()=>false;u.resolveStep=x=>x;u.currentBlueprintPlan=()=>null;u.tutFocus=()=>null;u.renderTut(true);assert.match(box.innerHTML,/Paying for growth/);assert.doesNotMatch(box.innerHTML,/You brought the yard back/);A.dispatch({type:'tutFlag',flag:'finAck'});lessonTick(A);assert.equal(A.s.lesson,null);assert.ok(A.s.lessonsDone.financing);u.renderTut(true);assert.match(box.innerHTML,/Rescue history/);assert.equal(A.s.debt.length,0);});
console.log(`${n} career integration test groups passed`);
