import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { makeScenario, makeSandbox, scenarioProgress } from '../../js/scenarios.js';
import { makeMaple } from '../../js/maple.js';
import { Sim } from '../../js/sim.js';
import { UI } from '../../js/ui.js';
import { installTutorial } from '../../js/tutorial.js';
import { comebackProgress, targetUnits, targetInService, unitInService, checkComeback, mapComebackReplacements } from '../../js/comeback.js';
import { loadRenderer } from '../performance/renderer-fixture.mjs';
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name)}
const fresh = seed => makeScenario('comeback',seed);
const reload = sim => new Sim(JSON.parse(JSON.stringify(sim.s)));
function restore(sim,path='owner',limit=10080){
 const s=sim.s, actions=[];
 if(path==='staff'&&!s.staff.some(st=>st.role==='porter'))assert.ok(sim.dispatch({type:'hire',role:'porter'}).ok);
 for(let i=0;i<limit&&s.scenario.status==='active';i++){
  // Real request actions; no removal of requests, artificial demand, disabled costs, or clock jumps.
  for(const c of [...s.convos]){const k=c.actions.findIndex(a=>!sim.requestActionDisabled(a)&&!a.action);if(k>=0){sim.dispatch({type:'convo',id:c.id,i:k});actions.push({request:c.key,choice:k});}}
  if(i%5===0){const t=s.tasks.find(t=>!t.assigned&&s.scenario.targets.some(x=>x.ids.includes(t.obj)));if(t){const r=sim.dispatch({type:path==='owner'?'ownerTask':'delegateTask',task:t.id,forceOwner:path==='owner'});if(r.ok)actions.push({t:s.t,task:t.id,assigned:t.assigned});}}
  sim.step();
 }
 assert.equal(s.scenario.status,'won');return actions;
}
function finish(sim,id,role='owner',aborted=false){const t=sim.s.tasks.find(t=>t.obj===id&&t.type==='makeready');assert.ok(t);if(role!=='owner'&&!sim.s.staff.some(st=>st.role===role))assert.ok(sim.dispatch({type:'hire',role}).ok);const ag=sim.s.agents.find(a=>a.role===role);sim.finishTask(t,ag,aborted);sim.poll();}
function ui(sim){const box={innerHTML:'',querySelector(){return null}},u=Object.create(UI.prototype);u.g={sim,rend:{setFocus(){}},audio:{unlock(){},play(){}}};u.$=()=>box;u.title=false;u.scMin=true;u.toasts=[];u.toast=()=>{};return {u,box}}
function click(u,a,v){u.onClick({target:{closest(){return {dataset:{a,v},closest(){return null}}}}});}

test('fresh valid property: six identified make-ready units, viable core, paused and normal costs',()=>{const sim=fresh(4401),s=sim.s;assert.equal(s.speed,0);assert.equal(s.cash,1150);assert.equal(s.creative,false);assert.equal(s.opts,undefined);assert.equal(s.tut.on,false);assert.equal(s.scenario.targets.length,6);assert.equal(Object.keys(s.leases).length,16);assert.equal(s.tasks.filter(t=>t.type==='makeready').length,6);assert.ok(s.scenario.targets.every(t=>targetUnits(s,t).length===1&&!s.objects[t.id].blocked));assert.equal(s.scenario.deadline,null);assert.equal(s.scenario.fail,null);assert.ok(sim.financialPosition().available>0);assert.ok(sim.financialPosition({extraDaily:12.5}).available<0);const snapshot=JSON.stringify(s);installTutorial(sim);assert.equal(JSON.stringify(s),snapshot);});
test('a hire or job assignment does not award a restoration or plan goal',()=>{const sim=fresh(4401);sim.dispatch({type:'hire',role:'porter'});sim.dispatch({type:'delegateTask',task:sim.s.tasks[0].id});assert.deepEqual(sim.s.scenario.earned,[false,false,false]);assert.equal(comebackProgress(sim).staff,0);});
test('successful owner work distinguishes target units; aborted and unrelated work give no credit',()=>{const sim=fresh(4401),ids=sim.s.scenario.targets.map(t=>t.id);finish(sim,ids[0],'owner',true);assert.deepEqual(sim.s.scenario.earned,[false,false,false]);sim.addTask({type:'makeready',need:'makeready',obj:ids[0],work:150});finish(sim,ids[0]);assert.deepEqual(sim.s.scenario.earned,[true,false,false]);sim.addTask({type:'makeready',need:'makeready',obj:ids[0],work:150});finish(sim,ids[0]);assert.equal(sim.s.scenario.ownerDone.length,1);finish(sim,ids[1]);assert.deepEqual(sim.s.scenario.earned,[true,true,false]);});
test('staff completion of one target job earns the plan without any owner restoration',()=>{const sim=fresh(4401);finish(sim,sim.s.scenario.targets[0].id,'porter');assert.deepEqual(sim.s.scenario.earned,[true,true,false]);assert.equal(sim.s.scenario.ownerDone.length,0);});
test('goals can complete out of order, and no deadline or random rental is required',()=>{const sim=fresh(4401);for(const t of sim.s.scenario.targets)sim.s.objects[t.id].commercial='ready';sim.poll();assert.deepEqual(sim.s.scenario.earned,[true,false,true]);finish(sim,sim.s.scenario.targets[0].id,'porter');assert.equal(sim.s.scenario.status,'won');assert.equal(sim.s.days.length,0);sim.s.t=999*1440;sim.scenarioCheck(sim.day);assert.equal(sim.s.scenario.status,'won');});
test('wing goal requires simultaneous serviceability, not six historical completions',()=>{const sim=fresh(4401),ts=sim.s.scenario.targets;finish(sim,ts[0].id);sim.s.objects[ts[0].id].commercial='unready';for(const t of ts.slice(1))finish(sim,t.id);assert.equal(sim.s.scenario.earned[2],false);sim.s.objects[ts[0].id].commercial='ready';sim.poll();assert.equal(sim.s.scenario.status,'won');sim.s.objects[ts[0].id].blocked=true;checkComeback(sim);assert.equal(comebackProgress(sim).restored,5);assert.equal(sim.s.scenario.earned[2],true);});
test('valid occupied and reserved restored units count separately from ready inventory',()=>{const sim=fresh(4401),ts=sim.s.scenario.targets;for(const t of ts)finish(sim,t.id);const [a,b]=ts.map(t=>sim.s.objects[t.id]);for(const [u,status]of [[a,'occupied'],[b,'reserved']]){const tenant=sim.id(),lease=sim.id();sim.s.tenants[tenant]={id:tenant,lease};sim.s.leases[lease]={id:lease,tenant,unit:u.id};u.lease=lease;u.commercial=status;}const p=comebackProgress(sim);assert.equal(p.restored,6);assert.equal(p.ready,4);assert.equal(p.occupied,1);assert.equal(p.reserved,1);delete sim.s.leases[a.lease];assert.equal(unitInService(sim.s,a),false);a.commercial='ready';assert.equal(unitInService(sim.s,a),false);});
test('deleting a target does not award it; explicit split maps full replacement footprint',()=>{const sim=fresh(4401),t=sim.s.scenario.targets[0];const r=sim.dispatch({type:'renovate',unit:t.id,kind:'split'});assert.ok(r.ok,r.msg);assert.equal(t.ids.length,2);assert.equal(targetInService(sim.s,t),false);finish(sim,t.ids[0]);assert.equal(targetInService(sim.s,t),false);finish(sim,t.ids[1]);assert.equal(targetInService(sim.s,t),true);assert.equal(comebackProgress(sim).restored,1);assert.equal(comebackProgress(sim).owner,1);const saved=reload(sim);assert.equal(saved.s.scenario.status,'active');assert.equal(comebackProgress(saved).restored,1);delete sim.s.objects[t.ids[0]];sim.markDirty();sim.rebuild();assert.equal(comebackProgress(sim).restored,0);});
test('replacement mapping rejects gaps, overlaps and wrong directions; partial rebuild can reconnect',()=>{const sim=fresh(4401),t=sim.s.scenario.targets[0],original={...sim.s.objects[t.id]};delete sim.s.objects[t.id];assert.equal(comebackProgress(sim).restored,0);const id=sim.id();sim.s.objects[id]={...original,id,w:1,commercial:'ready'};mapComebackReplacements(sim,[id]);assert.deepEqual(t.ids,[t.id]);sim.s.objects[id].w=2;sim.s.objects[id].dir=[-1,0];mapComebackReplacements(sim,[id]);assert.deepEqual(t.ids,[t.id]);sim.s.objects[id].dir=[1,0];mapComebackReplacements(sim,[id]);assert.deepEqual(t.ids,[id]);const r=sim.dispatch({type:'renovate',unit:id,kind:'split'});assert.ok(r.ok);const gone=t.ids[0],part={...sim.s.objects[gone]},other=t.ids[1];delete sim.s.objects[gone];const replacement=sim.id();sim.s.objects[replacement]={...part,id:replacement};mapComebackReplacements(sim,[replacement]);assert.deepEqual(t.ids,[other,replacement]);});
test('save/load before, during and after work preserves cash, assignments, goals and acknowledgement',()=>{let sim=fresh(4401);assert.deepEqual(reload(sim).s,sim.s);sim.dispatch({type:'hire',role:'porter'});sim.dispatch({type:'delegateTask',task:sim.s.tasks[0].id});for(let i=0;i<35;i++)sim.step();const cash=sim.s.cash,before=JSON.parse(JSON.stringify(sim.s));sim=reload(sim);assert.deepEqual(sim.s,before);assert.equal(sim.s.cash,cash);restore(sim,'staff');assert.ok(sim.dispatch({type:'comebackAck'}).ok);const done=JSON.parse(JSON.stringify(sim.s));sim=reload(sim);assert.deepEqual(sim.s,done);sim.poll();assert.equal(sim.s.scenario.acknowledged,true);assert.equal(sim.events.filter(e=>e.type==='scenario_end').length,0);});
test('malformed scenario progress fails safely without resetting the property or awarding success',()=>{for(const mutate of [s=>s.scenario.targets=null,s=>s.scenario.earned='won',s=>s.scenario.ownerDone=[999],s=>s.scenario.targets[0].ids=[],s=>s.scenario.targets[0].dir=[0,0],s=>s.scenario.targets[0].x=-1]){const sim=fresh(4401),cash=sim.s.cash;mutate(sim.s);const recovered=reload(sim);assert.equal(recovered.s.scenario.status,'unavailable');assert.equal(recovered.s.cash,cash);assert.equal(recovered.objs('unit').length,23);assert.equal(scenarioProgress(recovered).some(g=>g.met),false);recovered.step();}});
test('regular Maple, sandbox and other scenarios retain their ordinary mode and progress',()=>{for(const sim of [makeMaple(1),makeSandbox(),makeScenario('turnaround'),makeScenario('vertical'),makeScenario('climate')]){assert.notEqual(sim.s.scenario?.id,'comeback');assert.deepEqual(reload(sim).s,sim.s);sim.poll();}});
const runs=[];
test('both recovery paths complete across five seeds without cash injection, demand changes or loans',()=>{for(const path of ['owner','staff'])for(const seed of [4401,4402,4403,4404,4405]){const sim=fresh(seed),actions=restore(sim,path);assert.equal(comebackProgress(sim).restored,6);assert.equal(sim.s.loan.bal,0);assert.equal(sim.s.opts,undefined);assert.equal(sim.s.cash>=0,true);assert.equal(sim.s.ledger.some(l=>['inject','subsidy','loan'].includes(l.cat)),false);if(path==='staff')assert.equal(sim.s.scenario.ownerDone.length,0);const totals=sim.s.days.reduce((t,d)=>({...t,ownerWork:t.ownerWork+(d.ownerUsed||0),payroll:t.payroll+(d.payroll||0)}),{ownerWork:sim.s.staff[0].workUsed||0,payroll:sim.s.today.payroll});runs.push({path,seed,day:sim.day,minutes:sim.s.t-420,position:sim.financialPosition(),totals,ownerCompleted:sim.s.scenario.ownerDone.length,staffCompleted:sim.s.scenario.staffDone.length,actions});}});
test('Comeback panel keeps current inventory distinct, costs honest and close controls accessible in markup',()=>{const {u,box}=ui(fresh(4401));u.scMin=false;u.renderComeback(true);assert.match(box.innerHTML,/0 vacant ready · 0 occupied/);assert.match(box.innerHTML,/No upfront hiring fee/);assert.match(box.innerHTML,/\$12.50\/employed day/);assert.match(box.innerHTML,/7 AM/);assert.match(box.innerHTML,/Close Comeback panel/);assert.ok(box.innerHTML.indexOf('Close Comeback panel')<box.innerHTML.indexOf('Goals and recovery choices'));assert.doesNotMatch(box.innerHTML,/Day .* of null|Day null|undefined/);const css=readFileSync('css/game.css','utf8');assert.match(css,/#ui \.tut\.comeback \.ch \{ position:sticky/);assert.match(css,/#ui \.tut\.comeback \.btn \{ min-height:44px/);});
test('panel close restores prior speed and preserves manual Pause and other popup holds',()=>{for(const speed of [0,1,2,4]){const sim=fresh(4401),{u}=ui(sim);sim.s.speed=speed;u.scMin=false;u.renderComeback(true);assert.equal(sim.s.speed,0);click(u,'comebackClose');assert.equal(sim.s.speed,speed);}const sim=fresh(4401),{u}=ui(sim);sim.s.speed=2;u.scMin=false;u.renderComeback(true);u.requestSpeed(0);click(u,'comebackClose');assert.equal(sim.s.speed,0);sim.s.speed=1;u.scMin=false;u.renderComeback(true);u.pauseForPopup('convo');click(u,'comebackClose');assert.equal(sim.s.speed,0);u.resumePopup('convo');assert.equal(sim.s.speed,1);});
test('completion keeps same property and acknowledgement suppresses automatic reopening on load',()=>{const sim=fresh(4401);restore(sim);const {u,box}=ui(sim);u.renderComeback(true);assert.match(box.innerHTML,/You brought the yard back/);assert.equal(u.scMin,false);click(u,'comebackClose');assert.equal(sim.s.scenario.acknowledged,true);assert.equal(u.scMin,true);const {u:next}=ui(reload(sim));next.renderComeback(true);assert.equal(next.scMin,true);});
test('work and hire buttons open the existing relevant sections without hiring or replacing the game',()=>{const sim=fresh(4401),{u}=ui(sim);const calls=[];u.select=id=>calls.push(['select',id]);u.setTab=t=>calls.push(['tab',t]);u.jumpSection=s=>calls.push(['section',s]);click(u,'comebackWork');assert.deepEqual(calls.at(-1),['section','Work queue']);click(u,'comebackHire');assert.deepEqual(calls.at(-1),['section','Hire capacity']);assert.equal(sim.s.staff.length,1);assert.equal(u.hireRoleFocus,'porter');});
test('existing new-game safeguards and map gesture handlers remain wired',()=>{const main=readFileSync('js/main.js','utf8'),source=readFileSync('js/ui.js','utf8');assert.match(source,/case 'new': this.guardNew/);assert.match(main,/DOUBLE_TAP_MS\s*=\s*320/);assert.match(main,/game\.rend\.doubleTapZoom/);assert.match(source,/Number\.isFinite\(s.scenario.deadline\)/);});
const Renderer=await loadRenderer();
test('restoration visibly changes only target bodies; existing door/status cues and RNG are preserved',()=>{const sim=fresh(4401),r=new Renderer({clientWidth:393,clientHeight:720},sim),saved=JSON.stringify(sim.s);r.rebuildStatic();assert.equal(JSON.stringify(sim.s),saved);const bodies=r.anim.filter(a=>a.k==='comeback');assert.equal(bodies.length,6);assert.ok(bodies.every(a=>a.mesh.material===r.mat.comebackWorn));const t=sim.s.scenario.targets[0];finish(sim,t.id);const snap=JSON.stringify(sim.s);r.updateAnim(.016);assert.equal(JSON.stringify(sim.s),snap);assert.equal(bodies.find(a=>a.target.id===t.id).mesh.material,r.mat.comebackRestored);assert.equal(bodies.filter(a=>a.mesh.material===r.mat.comebackRestored).length,1);const door=r.anim.find(a=>a.k==='rollup'&&a.o.id===t.id),band=r.anim.find(a=>a.k==='unitStatus'&&a.o.id===t.id);assert.equal(door.mesh.material,r.statusMaterials.available);assert.equal(band.mesh.material,r.statusMaterials.available);assert.ok(r.mat.unitWall.color.getHexString()!==r.mat.comebackWorn.color.getHexString());});
mkdirSync('docs/qa/comeback-yard',{recursive:true});writeFileSync('docs/qa/comeback-yard/recovery-paths.json',JSON.stringify({device:'Native deterministic simulation; not browser or physical iPhone',runs},null,2));
console.log(`${n} Comeback Yard checks passed`);
