import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
import {diagnoseComplaint,diagnoseRequest} from '../../js/complaints.js';
let count=0,failed=0;const test=(name,f)=>{try{f();console.log('PASS '+name);count++;}catch(e){failed++;console.log('FAIL '+name+': '+e.message);}};
function fixture(){const sim=makeMaple(1004),u=sim.objs('unit').find(x=>x.access==='interior'),ag={id:901,unit:u.id,x:u.x,y:u.y,f:u.f||0,size:u.size};return{sim,u,ag};}
function uiFixture(sim){const ui=Object.create(UI.prototype),seen=[];ui.g={sim,audio:{unlock(){}},rend:{lookAt:(...a)=>seen.push(['camera',...a])}};ui.setTab=v=>seen.push(['tab',v]);ui.setView=v=>seen.push(['floor',v]);ui.select=v=>seen.push(['selection',v]);return{ui,seen};}
function click(ui,target){ui.onClick({target:{closest:()=>({dataset:{a:'complaintView',target:JSON.stringify(target)}})}});}
test('requested sizes remain separate at the same office',()=>{const {sim,ag}=fixture();sim.thought({...ag,size:'5x5'},'Nothing ready to rent today.');sim.thought({...ag,size:'10x20'},'Nothing ready to rent today.');assert.equal(sim.s.thoughts.filter(t=>t.text==='Nothing ready to rent today.').length,2);});
test('climate and standard requests remain separate at same office',()=>{const {sim,ag}=fixture();sim.thought(ag,'Nothing ready to rent today.','bad',{requestedClimate:false});sim.thought(ag,'Nothing ready to rent today.','bad',{requestedClimate:true});assert.equal(sim.s.thoughts.filter(t=>t.text==='Nothing ready to rent today.').length,2);});
test('negative and neutral reports cannot merge away a complaint',()=>{const {sim,ag}=fixture();sim.thought(ag,'The hallway is dark.','neutral');sim.thought(ag,'The hallway is dark.','bad');assert.equal(sim.s.thoughts.filter(t=>t.text==='The hallway is dark.').length,2);});
test('market inventory excludes irrelevant sizes and blocked ready stock',()=>{const {sim,ag}=fixture();const units=sim.objs('unit');for(const u of units){u.size='10x20';u.commercial='ready';}units[0].size='5x5';units[0].blocked=true;sim.thought({...ag,size:'5x5'},'Nothing ready to rent today.');const d=diagnoseComplaint(sim,sim.s.thoughts.at(-1));assert.match(d.cause,/5x5/);assert.match(d.cause,/0 accessible rent-ready/);assert.match(d.cause,/1 blocked/);});
test('missing request target never invents map origin',()=>{const {sim}=fixture();const d=diagnoseRequest(sim,{key:'gate404',obj:999999,text:'Gate failed'});assert.equal(d.target,null);assert.match(d.location,/unavailable/i);});
test('old malformed thought cannot issue NaN camera navigation',()=>{const {sim}=fixture();const d=diagnoseComplaint(sim,{text:'The hallway is dark.',kind:'bad'});assert.equal(d.target,null);});
test('expired thought cannot redirect a previously rendered View button',()=>{const {sim,u,ag}=fixture();sim.thought(ag,'The hallway is dark.');const d=diagnoseComplaint(sim,sim.s.thoughts.at(-1)),{ui,seen}=uiFixture(sim);sim.s.thoughts=[];click(ui,d.target);assert.deepEqual(seen.find(x=>x[0]==='camera'),['camera',u.x,u.y]);assert.ok(seen.some(x=>x[0]==='selection'&&x[1]===u.id));});
test('deleted object retains recorded camera position without selecting another object',()=>{const {sim,u}=fixture(),{ui,seen}=uiFixture(sim);const l={obj:u.id,x:u.x,y:u.y,f:0};delete sim.s.objects[u.id];click(ui,l);assert.ok(seen.some(x=>x[0]==='camera'));assert.ok(!seen.some(x=>x[0]==='selection'&&x[1]!==null));});
test('invalid navigation data leaves camera and floor untouched',()=>{const {sim}=fixture(),{ui,seen}=uiFixture(sim);for(const target of [{x:null,y:2,f:0},{x:999999,y:2,f:0},{x:2,y:2,f:99},null])click(ui,target);assert.equal(seen.length,0);});
test('feedback View buttons hold target snapshots rather than mutable array offsets',()=>{const {sim,ag}=fixture();sim.thought(ag,'Loading bays are full.');const {ui}=uiFixture(sim);assert.match(ui.feedbackSheet(),/data-target=/);assert.doesNotMatch(ui.feedbackSheet(),/data-a="complaintView" data-v=/);});
test('removed building/target is still identified in saved feedback',()=>{const {sim,u,ag}=fixture();sim.thought(ag,'The hallway is dark.');const t=sim.s.thoughts.at(-1);delete sim.s.objects[u.id];delete sim.s.objects[t.location.building];assert.match(diagnoseComplaint(sim,t).location,/removed/i);});
test('partial moveout request remains readable without a text crash',()=>{const {sim}=fixture();assert.ok(diagnoseRequest(sim,{key:'mo1'}));});
function bubbleFixture(){const {sim,ag}=fixture();sim.thought(ag,'The hallway is dark.');const th=sim.s.thoughts.at(-1),{ui,seen}=uiFixture(sim),handlers={},el={tabIndex:-1,setAttribute(){},setPointerCapture(id){this.captured=id;},addEventListener(k,f){handlers[k]=f;}};ui.feedbackSim=sim;ui.bindComplaintBubble(el,th);const send=(k,extra={})=>handlers[k]({pointerId:1,clientX:10,clientY:10,button:0,detail:1,...extra});return{sim,th,ui,seen,el,send};}
test('valid bubble tap opens the tapped report rather than latest report',()=>{const b=bubbleFixture();b.send('pointerdown');b.send('pointerup');b.send('click');assert.equal(b.ui.feedbackFocus,b.th);assert.deepEqual(b.seen.at(-1),['tab','feedback']);assert.equal(b.el.captured,1);});
test('bubble drag cannot open feedback on the following click',()=>{const b=bubbleFixture();b.send('pointerdown');b.send('pointermove',{clientX:40});b.send('pointerup',{clientX:40});b.send('click');assert.equal(b.seen.length,0);});
test('bubble pinch cannot turn either release into a click',()=>{const b=bubbleFixture();b.send('pointerdown');b.send('pointerdown',{pointerId:2});b.send('pointerup',{pointerId:2});b.send('pointerup');b.send('click');assert.equal(b.seen.length,0);});
test('cancellation rejects delayed click but allows a subsequent clean tap',()=>{const b=bubbleFixture();b.send('pointerdown');b.send('pointercancel');b.send('pointerup');b.send('click');assert.equal(b.seen.length,0);b.send('pointerdown');b.send('pointerup');b.send('click');assert.equal(b.seen.at(-1)[1],'feedback');});
test('release beyond threshold rejects tap even when move was missed',()=>{const b=bubbleFixture();b.send('pointerdown');b.send('pointerup',{clientY:40});b.send('click');assert.equal(b.seen.length,0);});
test('bubble keyboard activation remains available',()=>{const b=bubbleFixture();let prevented=false;b.send('keydown',{key:'Enter',preventDefault(){prevented=true;}});assert.ok(prevented);assert.equal(b.ui.feedbackFocus,b.th);});
test('bubble activation is disabled during construction and title screen',()=>{for(const mode of ['tool','title']){const b=bubbleFixture();b.ui[mode]=true;b.send('pointerdown');b.send('pointerup');b.send('click');assert.equal(b.seen.length,0);}});
test('old property bubble cannot open reports on another property',()=>{const b=bubbleFixture();b.ui.g.sim=makeMaple(99);b.send('pointerdown');b.send('pointerup');b.send('click');assert.equal(b.seen.length,0);});
test('property change clears bubbles, cooldowns and focused reports',()=>{const b=bubbleFixture();let removed=0;b.ui.bubbles=[{el:{remove(){removed++;}}}];b.ui.bubbleSeen=new Map([['old',1]]);b.ui.feedbackFocus=b.th;b.ui.g.sim=makeMaple(99);b.ui.syncFeedbackProperty();assert.equal(removed,1);assert.equal(b.ui.bubbles.length,0);assert.equal(b.ui.bubbleSeen.size,0);assert.equal(b.ui.feedbackFocus,null);});
test('expired selected report stays first even when history reaches its cap',()=>{const b=bubbleFixture();b.ui.feedbackFocus=b.th;b.sim.s.thoughts=[{...b.th,text:'No restroom in this building?',t:b.th.t+100}];const html=b.ui.feedbackSheet();assert.ok(html.indexOf('The hallway is dark.')<html.indexOf('No restroom in this building?'));});
test('wrong property snapshot is rejected without touching selection',()=>{const {sim}=fixture(),{ui,seen}=uiFixture(sim);ui.feedbackEpoch=2;ui.onClick({target:{closest:()=>({dataset:{a:'complaintView',property:'1',target:JSON.stringify({x:2,y:2,f:0})}})}});assert.equal(seen.length,0);});
test('new report grouping survives JSON save and resume',()=>{const {sim,ag}=fixture();for(const size of ['5x5','10x20'])sim.thought({...ag,size},'Nothing ready to rent today.');const restored=new Sim(JSON.parse(JSON.stringify(sim.s)));assert.equal(restored.s.thoughts.filter(t=>t.text==='Nothing ready to rent today.').length,2);});
test('malformed JSON target is ignored without crashing input handling',()=>{const {sim}=fixture(),{ui,seen}=uiFixture(sim);ui.onClick({target:{closest:()=>({dataset:{a:'complaintView',target:'{bad json'}})}});assert.equal(seen.length,0);});
test('right click and click without pointer sequence do not open bubble help',()=>{const b=bubbleFixture();b.send('click');b.send('pointerdown',{button:2});b.send('pointerup',{button:2});b.send('click');assert.equal(b.seen.length,0);});
test('a valid pointer click is consumed once',()=>{const b=bubbleFixture();b.send('pointerdown');b.send('pointerup');b.send('click');const n=b.seen.length;b.send('click');assert.equal(b.seen.length,n);});
test('request-help opens its request first in the scrolling feedback sheet',()=>{const {sim,ag}=fixture(),{ui}=uiFixture(sim);ui.feedbackSim=sim;sim.thought(ag,'The hallway is dark.');sim.s.convos=[{id:8,key:'rate8',text:'Rate question',t:1},{id:9,key:'gate9',text:'Gate question',t:2}];ui.onClick({target:{closest:()=>({dataset:{a:'requestHelp',id:'9'}})}});const h=ui.feedbackSheet();assert.ok(h.indexOf('Gate question')<h.indexOf('Rate question'));assert.ok(h.indexOf('Gate question')<h.indexOf('The hallway is dark.'));});
test('feedback escapes customer text and object names containing markup',()=>{const {sim,u,ag}=fixture(),{ui}=uiFixture(sim);u.name='<img src=x onerror=alert(1)>';sim.thought(ag,'The hallway is dark.');sim.s.convos=[{id:8,key:'rate8',obj:u.id,text:'<script>unsafe</script>',t:1}];const h=ui.feedbackSheet();assert.doesNotMatch(h,/<img|<script>/);assert.match(h,/&lt;script&gt;/);assert.match(h,/&lt;img/);});
test('upper-floor report switches to a supported upper floor',()=>{const {sim,u}=fixture(),{ui,seen}=uiFixture(sim);sim.objs('shell')[0].floors=2;click(ui,{obj:u.id,x:u.x,y:u.y,f:1});assert.ok(seen.some(x=>x[0]==='floor'&&x[1]===1));});
test('removed upper floor safely falls back to ground view',()=>{const {sim,u}=fixture(),{ui,seen}=uiFixture(sim);click(ui,{obj:u.id,x:u.x,y:u.y,f:1});assert.ok(seen.some(x=>x[0]==='floor'&&x[1]===0));});
test('routine bubble cooldown storage remains bounded under many locations',()=>{const previous=globalThis.document;globalThis.document={createElement(){return{setAttribute(){},addEventListener(){},remove(){}};}};try{const {sim}=fixture(),{ui}=uiFixture(sim);ui.phone=()=>true;ui.bubRoot={appendChild(){}};for(let i=0;i<400;i++)ui.addBubble({text:'Nothing ready to rent today.',kind:'bad',t:i,ag:i,location:{x:i%sim.s.W,y:Math.floor(i/sim.s.W),f:0},requestedSize:'5x5'});assert.ok(ui.bubbleSeen.size<=128);assert.ok(ui.bubbles.length<=2);}finally{globalThis.document=previous;}});
test('loading report for upstairs unit keeps camera on ground-floor bays',()=>{const {sim,u}=fixture(),{ui,seen}=uiFixture(sim);u.f=1;sim.objs('shell')[0].floors=2;click(ui,{obj:u.id,x:20,y:15,f:0});assert.deepEqual(seen.find(x=>x[0]==='camera'),['camera',20,15]);assert.ok(seen.some(x=>x[0]==='floor'&&x[1]===0));assert.ok(!seen.some(x=>x[0]==='selection'&&x[1]===u.id));});
console.log(`${count} hardening checks passed; ${failed} failed`);if(failed)process.exitCode=1;
