import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {G} from '../../js/data.js';
import {diagnoseComplaint,reviewRemedy} from '../../js/complaints.js';
let n=0;function test(name,fn){fn();console.log('PASS '+name);n++;}
function fixture(){const sim=makeMaple(1),u=sim.objs('unit').find(x=>x.access==='interior'),ag={id:999,kind:'cust',unit:u.id,f:0,x:u.x,y:u.y,exp:{walk:0}},v={id:998};return{sim,u,ag,v};}
function occupy(sim,types){sim.s.vehicles=sim.s.ground.map((g,i)=>types.includes(g)?{id:i,dest:i}:null).filter(Boolean);}
test('marked overflow parking succeeds silently',()=>{const {sim,ag,v}=fixture();occupy(sim,[G.LOADING]);const dest=sim.chooseDest(ag,v);assert.equal(sim.s.ground[dest],G.PARKING);assert.equal(ag.exp.walk,10);assert.equal(sim.s.thoughts.length,0);});
test('asphalt overflow succeeds silently when marked parking also fills',()=>{const {sim,ag,v}=fixture();occupy(sim,[G.LOADING,G.PARKING]);const dest=sim.chooseDest(ag,v);assert.equal(sim.s.ground[dest],G.ASPHALT);assert.equal(ag.exp.walk,10);assert.equal(sim.s.thoughts.length,0);});
test('true shortage retains existing loading destination and precise cause',()=>{const {sim,u,ag,v}=fixture();occupy(sim,[G.LOADING,G.PARKING,G.ASPHALT]);const dest=sim.chooseDest(ag,v),th=sim.s.thoughts.at(-1);assert.equal(sim.s.ground[dest],G.LOADING);assert.equal(th.overflowAvailable,false);assert.equal(th.loadingBays,4);assert.equal(th.location.obj,u.id);assert.match(diagnoseComplaint(sim,th).cause,/no free reachable overflow/);assert.equal(ag.exp.walk,0);});
test('same visitor cannot spam same shortage or inflate grouped count',()=>{const {sim,ag,v}=fixture();occupy(sim,[G.LOADING,G.PARKING,G.ASPHALT]);sim.chooseDest(ag,v);sim.s.t+=25;sim.chooseDest(ag,v);assert.equal(sim.s.thoughts.length,1);assert.equal(sim.s.thoughts[0].n,undefined);});
test('different visitors still count real repeated shortages',()=>{const {sim,ag,v}=fixture();occupy(sim,[G.LOADING,G.PARKING,G.ASPHALT]);sim.chooseDest(ag,v);sim.chooseDest({...ag,id:1000,complaintKeys:[]},v);assert.equal(sim.s.thoughts.length,1);assert.equal(sim.s.thoughts[0].n,2);});
test('per-visitor suppression survives save reload',()=>{const {sim,ag}=fixture();sim.s.agents.push(ag);sim.thought(ag,'The hallway is dark.');const restored=new Sim(JSON.parse(JSON.stringify(sim.s)));restored.s.t+=25;restored.thought(restored.s.agents.find(x=>x.id===ag.id),'The hallway is dark.');assert.equal(restored.s.thoughts.length,1);});
test('new location and distinct failure remain reportable for same visitor',()=>{const {sim,u,ag}=fixture();sim.thought(ag,'The hallway is dark.');ag.unit=sim.objs('unit').find(x=>x.id!==u.id).id;sim.thought(ag,'The hallway is dark.');sim.thought(ag,"I can't reach my unit.");assert.equal(sim.s.thoughts.length,3);});
test('historical overflow reports explain successful fallback honestly',()=>{const {sim,ag}=fixture();sim.thought(ag,'Loading bays are full.','bad',{overflowAvailable:true,loadingBays:4});assert.match(diagnoseComplaint(sim,sim.s.thoughts.at(-1)).cause,/did not prevent parking/);});
test('cart stock differentiates busy, displaced and damaged local carts read-only',()=>{const {sim,ag}=fixture();const c=sim.objs('corral')[0];ag.corral=c.id;sim.s.carts=[{id:1,home:c.id,corral:null,st:'inuse',cond:1},{id:2,home:c.id,st:'stranded',cond:1},{id:3,home:c.id,st:'damaged',cond:0}];sim.s.policies.porterCarts=false;sim.thought(ag,`No carts at ${c.name}.`);const before=JSON.stringify(sim.s),d=diagnoseComplaint(sim,sim.s.thoughts.at(-1));assert.match(d.cause,/0 claimable here, 1 in use, 1 stranded, 1 damaged/);assert.match(d.remedy,/switched off/);assert.equal(JSON.stringify(sim.s),before);});
test('restroom cleaning guidance identifies staffing gap without doing work',()=>{const {sim,ag}=fixture();const rr={id:9991,type:'restroom',x:ag.x,y:ag.y,f:0,dirt:0.9,cstate:'operating'};sim.s.objects[rr.id]=rr;sim.s.tasks.push({id:991,type:'cleanroom',need:'clean',obj:rr.id,work:20,total:20});sim.thought(ag,'That restroom needs cleaning.','bad',{location:{obj:rr.id,x:rr.x,y:rr.y,f:0}});const before=JSON.stringify(sim.s),d=diagnoseComplaint(sim,sim.s.thoughts.at(-1));assert.match(d.remedy,/Hire one/);assert.equal(JSON.stringify(sim.s),before);});
test('all negative property review dimensions have remedies without invented locations',()=>{for(const dim of ['security','cleanliness','convenience','service','value','access'])assert.ok(reviewRemedy(dim).length>40);assert.equal(reviewRemedy(null),'');});
console.log(`${n} capacity regression checks passed`);
