import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
function fixture(){const sim=makeMaple(20261004),s=sim.s;s.mode='sandbox';s.tut={on:false,done:true,flags:{}};s.t=600;s.open=true;s.tasks=[];s.officeQ=[];s.opts={demand:0,wear:0,costs:1};s.policies.ownerChores=false;for(const d of s.dirt)d.fill(0);s.staff=s.staff.filter(st=>st.role==='owner');s.agents=[];for(const st of s.staff)sim.spawnStaffAgent(st);sim.ensure();return sim;}
function light(sim){const o=sim.objs('light').find(o=>sim.taskCell({obj:o.id}));o.cond=.4;return o;}
function repair(sim){return sim.ensureRepairTask(light(sim));}
function hire(sim,role){assert.equal(sim.dispatch({type:'hire',role}).ok,true);return sim.s.staff.find(st=>st.role===role);}
function ui(sim){const u=Object.create(UI.prototype);u.g={sim};return u;}
test('Tech repairs accessible equipment automatically without Owner action',()=>{const sim=fixture(),t=repair(sim),st=hire(sim,'tech');const cash=sim.s.cash;for(let i=0;i<500 && sim.s.tasks.includes(t);i++)sim.step();assert.ok(!sim.s.tasks.includes(t));assert.equal(sim.s.objects[t.obj].cond,1);assert.equal(sim.s.objects[t.obj].quickFix,false);assert.equal(sim.s.cash,cash);assert.equal(sim.s.staff.find(st=>st.role==='owner').workUsed||0,0);assert.ok(st.workUsed>0)});
test('explicit delegation uses existing role capacity and leaves Owner at office',()=>{const sim=fixture(),t=repair(sim);hire(sim,'tech');const owner=sim.s.staff[0];sim.syncStaffWork(owner);const before=owner.workUsed;assert.equal(sim.dispatch({type:'delegateTask',task:t.id}).ok,true);assert.equal(owner.workUsed,before);assert.equal(sim.s.agents.find(a=>a.sid===owner.id).st,'office');assert.equal(sim.s.staff.find(st=>st.id===t.assigned).role,'tech')});
test('Owner automatic chores yield to available Porter regardless of update order',()=>{const sim=fixture();sim.s.policies.ownerChores=true;hire(sim,'porter');const u=sim.objs('unit').find(u=>sim.taskCell({obj:u.id}));const t=sim.addTask({type:'makeready',need:'makeready',obj:u.id,work:150,label:'Turnover'});const owner=sim.s.agents.find(a=>a.role==='owner'),porter=sim.s.agents.find(a=>a.role==='porter');sim.updateStaff(owner);assert.equal(owner.task,null);sim.updateStaff(porter);assert.equal(porter.task,t.id)});
test('Owner can still help when hired Porter is busy or out of capacity',()=>{for(const reason of ['busy','capacity']){const sim=fixture();sim.s.policies.ownerChores=true;const st=hire(sim,'porter'),ag=sim.s.agents.find(a=>a.sid===st.id);if(reason==='busy')ag.task=999;else {st.workDay=sim.day;st.workUsed=8;}const u=sim.objs('unit').find(u=>sim.taskCell({obj:u.id})),t=sim.addTask({type:'makeready',need:'makeready',obj:u.id,work:150,label:'Turnover'});const owner=sim.s.agents.find(a=>a.role==='owner');sim.updateStaff(owner);assert.equal(owner.task,t.id)}});
test('Owner may still explicitly choose a job when a Porter is available',()=>{const sim=fixture();hire(sim,'porter');const u=sim.objs('unit').find(u=>sim.taskCell({obj:u.id}));const t=sim.addTask({type:'makeready',need:'makeready',obj:u.id,work:150,label:'Turnover'});assert.ok(sim.dispatch({type:'ownerTask',task:t.id}).ok);assert.equal(t.assigned,sim.s.staff[0].id)});
test('no Tech produces an actionable hire recommendation, not a false assignment',()=>{const sim=fixture(),t=repair(sim);hire(sim,'porter');const before=JSON.stringify(sim.s);assert.equal(sim.taskDelegation(t).status,'missing');assert.equal(JSON.stringify(sim.s),before);assert.equal(sim.dispatch({type:'delegateTask',task:t.id}).ok,false);assert.equal(t.assigned,null);assert.match(ui(sim).delegationHtml(t),/Review Tech hire/)});
test('off-shift, busy, exhausted and unreachable staff have distinct explanations',()=>{const sim=fixture(),t=repair(sim),st=hire(sim,'tech'),ag=sim.s.agents.find(a=>a.sid===st.id);sim.s.t=21*60;assert.equal(sim.taskDelegation(t).status,'offshift');sim.s.t=600;ag.task=999;assert.equal(sim.taskDelegation(t).status,'busy');ag.task=null;st.workDay=sim.day;st.workUsed=8;assert.equal(sim.taskDelegation(t).status,'capacity');st.workUsed=0;t.unreachable=sim.s.t;assert.equal(sim.taskDelegation(t).status,'route');assert.equal(sim.dispatch({type:'delegateTask',task:t.id}).ok,false)});
test('failed route refunds Tech capacity without altering Owner or cash',()=>{const sim=fixture(),t=repair(sim),st=hire(sim,'tech'),cash=sim.s.cash;sim.goTo=()=>false;assert.equal(sim.dispatch({type:'delegateTask',task:t.id}).ok,false);assert.equal(st.workUsed,0);assert.equal(t.assigned,null);assert.equal(sim.s.staff[0].workUsed||0,0);assert.equal(sim.s.cash,cash)});
test('assigned and vendor jobs cannot be taken over or billed again',()=>{const sim=fixture(),t=repair(sim);hire(sim,'tech');assert.ok(sim.dispatch({type:'callVendor',task:t.id}).ok);const cash=sim.s.cash;assert.equal(sim.dispatch({type:'delegateTask',task:t.id}).ok,false);assert.equal(t.assigned,'vendor');assert.equal(sim.s.cash,cash)});
test('Owner quick fix stays temporary; inspector does not invite redundant Owner service',()=>{const sim=fixture(),t=repair(sim),o=sim.s.objects[t.obj];sim.finishTask(t,sim.s.agents.find(a=>a.role==='owner'));assert.equal(o.cond,.72);assert.equal(o.quickFix,true);const html=ui(sim).taskActions(o);assert.doesNotMatch(html,/Owner: service now/);assert.match(html,/Another quick fix will not restore/);assert.match(html,/Review Tech hire/);const u=ui(sim);u.computePins();assert.equal(u.pinList.filter(p=>p.k==='repair'&&p.id===o.id).length,0)});
test('Tech can fully restore a temporary fix and delegateTaskFor cannot create work without staff',()=>{const sim=fixture(),o=light(sim);o.cond=.72;o.quickFix=true;assert.equal(sim.dispatch({type:'delegateTaskFor',obj:o.id}).ok,false);assert.equal(sim.s.tasks.length,0);hire(sim,'tech');assert.ok(sim.dispatch({type:'delegateTaskFor',obj:o.id}).ok);const t=sim.s.tasks.find(t=>t.obj===o.id);for(let i=0;i<500 && sim.s.tasks.includes(t);i++)sim.step();assert.equal(o.cond,1);assert.equal(o.quickFix,false)});
test('Clerk keeps office coverage while Owner repairs; wages unchanged',()=>{const sim=fixture();const t=repair(sim);assert.ok(sim.dispatch({type:'ownerTask',task:t.id}).ok);assert.equal(sim.officeServers(),0);const st=hire(sim,'clerk');assert.equal(st.wage,15);assert.equal(sim.officeServers(),1);assert.equal(ui(sim).officeCoverageHtml(),'')});
test('delegated work survives existing JSON save format and completes once',()=>{const sim=fixture(),t=repair(sim);hire(sim,'tech');assert.ok(sim.dispatch({type:'delegateTask',task:t.id}).ok);const restored=new Sim(JSON.parse(JSON.stringify(sim.s)));const originalCash=restored.s.cash;for(let i=0;i<500&&restored.s.tasks.some(x=>x.id===t.id);i++)restored.step();assert.equal(restored.s.objects[t.obj].cond,1);assert.equal(restored.s.tasks.some(x=>x.id===t.id),false);assert.equal(restored.s.cash,originalCash)});
console.log(`${checks} delegation regressions passed`);
