import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.log('FAIL '+name+': '+e.message);}}
function fixture(){const sim=makeMaple(20261004),u=sim.objs('unit').find(o=>o.access==='interior');const ag={id:900,unit:u.id,x:u.x,y:u.y,f:0,size:u.size};sim.thought(ag,'The hallway is dark.');const th=sim.events.find(e=>e.type==='thought');const ui=Object.create(UI.prototype),opened=[];ui.g={sim,audio:{unlock(){}}};ui.select=()=>{};ui.setTab=t=>opened.push(t);ui.feedbackSim=sim;const handlers={},el={setAttribute(){},setPointerCapture(){},addEventListener(k,v){handlers[k]=v;}};ui.bindComplaintBubble(el,th);const send=(name,e={})=>handlers[name]?.({pointerId:1,clientX:10,clientY:10,detail:1,button:0,...e});const global=(phase,id)=>ui.trackFeedbackPointer?.({pointerId:id},phase);return{sim,u,ag,th,ui,el,handlers,send,global,opened};}
test('bubble+map multitouch rejects click even after other finger releases',()=>{const f=fixture();f.global('down',1);f.send('pointerdown');f.global('down',2);f.global('up',2);f.global('up',1);f.send('pointerup');f.send('click');assert.equal(f.opened.length,0);});
test('map-first then bubble-second gesture does not open feedback',()=>{const f=fixture();f.global('down',2);f.global('down',1);f.send('pointerdown');f.global('up',2);f.global('up',1);f.send('pointerup');f.send('click');assert.equal(f.opened.length,0);});
test('lost pointer capture rejects delayed click and next clean tap works',()=>{const f=fixture();f.send('pointerdown');f.send('lostpointercapture');f.send('pointerup');f.send('click');assert.equal(f.opened.length,0);f.send('pointerdown');f.send('pointerup');f.send('click');assert.equal(f.opened.length,1);});
test('focused report keeps latest grouped repeat count',()=>{const f=fixture();f.ui.feedbackFocus=f.th;f.sim.thought(f.ag,'The hallway is dark.');assert.match(f.ui.feedbackSheet(),/The hallway is dark\. ×2/);});
test('opening request guidance resets previous feedback scroll position',()=>{const f=fixture(),body={scrollTop:500};f.sim.s.convos=[{id:99,key:'gate99',obj:f.u.id,text:'Gate report',t:1}];const box={innerHTML:'old',firstChild:{classList:{add(){}}},querySelector(s){return s==='.body'?body:null;}};f.ui.$=()=>box;f.ui.sheetKey='feedback';f.ui.tab='feedback';f.ui.setTab=t=>{f.ui.tab=t;f.ui.renderSheet(true);};f.ui.onClick({target:{closest:()=>({dataset:{a:'requestHelp',id:'99'}})}});assert.equal(body.scrollTop,0);});
test('actual upstairs elevator fault records the waiting floor',()=>{const f=fixture(),el={id:999,type:'elevator',x:f.u.x,y:f.u.y,f:0,cstate:'operating',cond:0,q:[[],[900]],riders:[],convoed:true};f.sim.s.objects[el.id]=el;f.sim.s.agents.push({...f.ag,kind:'cust',f:1,elev:el.id,elevT0:0,exp:{elev:0}});f.sim.s.t=5;f.sim.updateElevator(el);const th=f.sim.s.thoughts.at(-1);assert.equal(th.text,'The elevator is out of service.');assert.equal(th.location.f,1);assert.equal(th.location.obj,el.id);});
test('zero-detail delayed click cannot bypass pointer cancellation',()=>{const f=fixture();f.send('pointerdown');f.send('pointercancel');f.send('click',{detail:0});assert.equal(f.opened.length,0);});
test('background reset rejects pending click and permits a fresh solo touch',()=>{const f=fixture();f.global('down',1);f.send('pointerdown');f.ui.resetFeedbackPointers();f.send('pointerup');f.send('click');f.send('click',{detail:0});assert.equal(f.opened.length,0);f.global('down',2);f.send('pointerdown',{pointerId:2});f.global('up',2);f.send('pointerup',{pointerId:2});f.send('click');assert.equal(f.opened.length,1);});
test('post-release interruption invalidates a delayed pointer click',()=>{const f=fixture();f.global('down',1);f.send('pointerdown');f.global('up',1);f.send('pointerup');f.ui.resetFeedbackPointers();f.send('click');assert.equal(f.opened.length,0);});
test('normal capture release after valid pointerup keeps click eligible',()=>{const f=fixture();f.global('down',1);f.send('pointerdown');f.global('up',1);f.send('pointerup');f.send('lostpointercapture');f.send('click');assert.equal(f.opened.length,1);});
test('standalone assistive click and explicit keyboard remain usable',()=>{const f=fixture();f.send('click',{detail:0});assert.equal(f.opened.length,1);f.send('pointerdown');f.send('pointercancel');f.send('keydown',{key:'Enter',preventDefault(){}});assert.equal(f.opened.length,2);});
test('global pointer bookkeeping clears after many mixed-target gestures',()=>{const f=fixture();for(let i=0;i<100;i++){f.global('down',i*2);f.global('down',i*2+1);f.global('cancel',i*2);f.global('up',i*2+1);}assert.equal(f.ui.feedbackPointers.size,0);});
test('focused repeat count remains current after JSON resume',()=>{const f=fixture();f.sim.thought(f.ag,'The hallway is dark.');const r=new Sim(JSON.parse(JSON.stringify(f.sim.s)));f.ui.g.sim=r;f.ui.feedbackSim=r;f.ui.feedbackFocus=f.th;assert.match(f.ui.feedbackSheet(),/×2/);});
test('upper-floor elevator snapshot survives save without depending on customer',()=>{const f=fixture();f.sim.s.objects[999]={id:999,type:'elevator',f:0,x:18,y:5};f.sim.thought({...f.ag,elev:999,f:1},'The elevator has no power.');const saved=new Sim(JSON.parse(JSON.stringify(f.sim.s)));assert.equal(saved.s.thoughts.at(-1).location.f,1);assert.equal(saved.s.thoughts.at(-1).location.obj,999);});
test('UI constructor wires document-wide capture and lifecycle reset once',()=>{const priorD=globalThis.document,priorW=globalThis.window,priorTitle=UI.prototype.showTitle,events={},windowEvents={};const root={addEventListener(){}};globalThis.document={getElementById:()=>root,addEventListener(k,f,opts){events[k]={f,opts};},hidden:false};globalThis.window={addEventListener(k,f){windowEvents[k]=f;}};UI.prototype.showTitle=function(){};try{const {sim}=fixture();const ui=new UI({sim});for(const name of ['pointerdown','pointerup','pointercancel'])assert.equal(events[name].opts.capture,true);events.pointerdown.f({pointerId:1});assert.equal(ui.feedbackPointers.size,1);windowEvents.blur();assert.equal(ui.feedbackPointers.size,0);events.pointerdown.f({pointerId:2});globalThis.document.hidden=true;events.visibilitychange.f();assert.equal(ui.feedbackPointers.size,0);}finally{UI.prototype.showTitle=priorTitle;globalThis.document=priorD;globalThis.window=priorW;}});
test('all three-touch press/release orders reject help and recover cleanly',()=>{const perms=[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]];for(const down of perms)for(const up of perms){const f=fixture();for(const id of down){f.global('down',id);if(id===1)f.send('pointerdown');}for(const id of up){f.global('up',id);if(id===1)f.send('pointerup');}f.send('click');f.send('click',{detail:0});assert.equal(f.opened.length,0,`orders ${down}/${up}`);f.global('down',4);f.send('pointerdown',{pointerId:4});f.global('up',4);f.send('pointerup',{pointerId:4});f.send('click');assert.equal(f.opened.length,1);assert.equal(f.ui.feedbackPointers.size,0);}});
console.log(`${passed} feedback checks passed; ${failed} failed`);if(failed)process.exitCode=1;
