import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
import {PerformanceStats} from '../../js/performance.js';
import {readFileSync} from 'node:fs';
let count=0;const test=(n,f)=>{f();console.log('PASS '+n);count++};
function fixture(){const sim=makeMaple(20261004);sim.s.tut={on:false,done:true};sim.s.policies.ownerChores=false;sim.s.t=600;const owner=sim.s.staff.find(x=>x.role==='owner'),ag=sim.s.agents.find(x=>x.sid===owner.id),first=sim.s.tasks.find(x=>x.type==='makeready');const spare=sim.objs('unit').find(x=>x.id!==first.obj);const second=sim.addTask({type:'makeready',need:'makeready',obj:spare.id,label:'Queued turnover',work:150});return{sim,owner,ag,first,second};}
function hire(sim,role){assert.ok(sim.dispatch({type:'hire',role}).ok);return sim.s.staff.filter(x=>x.role===role).at(-1)}
test('failed handoff retains Owner queue and exact booking, without double refund',()=>{const f=fixture();f.sim.dispatch({type:'ownerTask',task:f.first.id});f.sim.dispatch({type:'ownerTask',task:f.second.id});hire(f.sim,'porter');const left=f.sim.workRemaining(f.owner);const booking=f.second.workBooked;f.sim.goTo=()=>false;f.sim.rebalanceOwnerQueue();assert.equal(f.second.assigned,f.owner.id);assert.equal(f.second.workBooked,booking);assert.equal(f.sim.workRemaining(f.owner),left);assert.ok(f.ag.queue.includes(f.second.id));f.sim.rebalanceOwnerQueue();assert.equal(f.sim.workRemaining(f.owner),left)});
test('queued Owner override survives hire, rebalancing and old-format JSON resume',()=>{const f=fixture();f.sim.dispatch({type:'ownerTask',task:f.first.id});f.sim.dispatch({type:'ownerTask',task:f.second.id,forceOwner:true});hire(f.sim,'porter');f.sim.rebalanceOwnerQueue();const r=new Sim(JSON.parse(JSON.stringify(f.sim.s)));r.rebalanceOwnerQueue();assert.equal(r.s.tasks.find(x=>x.id===f.second.id).assigned,f.owner.id);assert.equal(r.workRemaining(r.s.staff.find(x=>x.id===f.owner.id)),3)});
test('active Owner work stays assigned when staff hired',()=>{const f=fixture();f.sim.dispatch({type:'ownerTask',task:f.first.id});hire(f.sim,'porter');f.sim.rebalanceOwnerQueue();assert.equal(f.ag.task,f.first.id);assert.equal(f.first.assigned,f.owner.id)});
test('busy staff route failure does not reserve hours or silently send Owner',()=>{const f=fixture();const p=hire(f.sim,'porter');f.sim.dispatch({type:'ownerTask',task:f.first.id});const left=f.sim.workRemaining(p);f.sim.goTo=()=>false;const r=f.sim.dispatch({type:'ownerTask',task:f.second.id});assert.equal(r.ok,false);assert.match(r.msg,/blocked by access/);assert.equal(f.sim.workRemaining(p),left);assert.equal(f.sim.workRemaining(f.owner),8);assert.equal(f.second.assigned,null)});
test('next-day exhausted queued worker retains assignment until capacity becomes available',()=>{const f=fixture(),p=hire(f.sim,'porter');f.sim.dispatch({type:'ownerTask',task:f.first.id});f.sim.dispatch({type:'ownerTask',task:f.second.id});const pa=f.sim.s.agents.find(x=>x.sid===p.id);f.sim.s.t+=1440;p.workDay=f.sim.day;p.workUsed=8;pa.task=null;pa.st='idle';f.sim.updateStaff(pa);assert.ok(pa.queue.includes(f.second.id));assert.equal(f.second.assigned,p.id);assert.ok(f.second.queued);p.workUsed=0;for(let i=0;i<3&&!pa.task;i++)f.sim.updateStaff(pa);assert.equal(pa.task,f.second.id);assert.equal(f.sim.workRemaining(p),5.5)});
test('route change after queueing refunds worker once and releases blocked job',()=>{const f=fixture(),p=hire(f.sim,'porter');f.sim.dispatch({type:'ownerTask',task:f.first.id});f.sim.dispatch({type:'ownerTask',task:f.second.id});const pa=f.sim.s.agents.find(x=>x.sid===p.id);pa.task=null;pa.st='idle';f.sim.s.t=601;f.sim.goTo=()=>false;f.sim.updateStaff(pa);assert.equal(f.second.assigned,null);assert.equal(f.second.workBooked,null);assert.equal(f.sim.workRemaining(p),5.5)});
test('Manager and Clerk cannot take Porter/Tech jobs',()=>{const f=fixture();hire(f.sim,'manager');hire(f.sim,'clerk');assert.equal(f.sim.staffForTask(f.second),null)});
test('work board explains queued capacity, shifts and current office coverage',()=>{const f=fixture(),p=hire(f.sim,'porter');f.sim.dispatch({type:'ownerTask',task:f.first.id});f.sim.dispatch({type:'ownerTask',task:f.second.id});const u=Object.create(UI.prototype);u.g={sim:f.sim};assert.match(u.jobWait(f.second),/Queued behind/);f.sim.s.t=21*60;assert.match(u.jobWait(f.second),/next 7 AM/);assert.match(u.officeCoverageHtml(),/Office covered by Owner/);const clerk=hire(f.sim,'clerk');assert.match(u.officeCoverageHtml(),/8 AM–6 PM/);f.sim.s.t=600;assert.match(u.officeCoverageHtml(),/Clerk/);assert.ok(clerk)});
test('diagnostic windows isolate idle/battery and include every skipped callback CPU',()=>{const p=new PerformanceStats(4);p.enabled=true;for(let i=0;i<3;i++)p.record({at:i*16,mode:'active',rafMs:16,frameMs:16,drawn:true,simMs:2,renderMs:1,uiMs:1,info:{calls:99}});p.record({at:48,mode:'battery',rafMs:16,drawn:false,simMs:8});p.record({at:64,mode:'battery',rafMs:16,frameMs:32,drawn:true,simMs:4,renderMs:1,uiMs:1});p.record({at:314,mode:'idle',rafMs:16,frameMs:250,drawn:true,simMs:1});const s=p.snapshot();assert.equal(s.modes.active.frameMs.p95,16);assert.equal(s.modes.battery.simulationTotalMs,12);assert.equal(s.modes.battery.cpuMs.simulation,6);assert.equal(s.modes.battery.skipped,1);assert.equal(s.modes.idle.frameMs.p95,250);assert.equal(s.modes.active.windowMs,32);assert.match(p.text(),/RAF.*draws.*skipped/)});
test('diagnostic panel lives inside scrolling menu rather than a fixed overlay',()=>{const ui=readFileSync('js/ui.js','utf8'),css=readFileSync('css/game.css','utf8'),html=readFileSync('index.html','utf8');assert.match(ui,/<details class="performance-panel">/);assert.match(css,/#fps \{ position: static/);assert.doesNotMatch(html,/id="fps"/)});
console.log(`${count} management/diagnostic regressions passed`);
