import assert from 'node:assert/strict';
import {UI} from '../../js/ui.js';
import {BEATS} from '../../js/tutorial.js';
import {makeMaple} from '../../js/maple.js';
let n=0;const test=(name,f)=>{f();console.log('PASS '+name);n++;};
function fixture(speed=4){const sim=makeMaple(15);sim.s.speed=speed;const ui=Object.create(UI.prototype);ui.g={sim,audio:{unlock(){}},rend:{setSelection(){}}};ui.title=false;ui.sfx=()=>{};ui.toast=()=>{};return{ui,sim};}
for(const speed of [0,1,2,4])test('nested overlays resume safely at 1x from '+speed,()=>{const {ui,sim}=fixture(speed);ui.pauseForPopup('panel');ui.pauseForPopup('modal');assert.equal(sim.s.speed,0);ui.resumePopup('panel');assert.equal(sim.s.speed,0);ui.resumePopup('modal');assert.equal(sim.s.speed,1);});
test('popup closure uses intentional 1x policy after a Pause tap',()=>{const {ui,sim}=fixture();ui.pauseForPopup('panel');ui.onClick({target:{closest:()=>({dataset:{a:'speed',v:'0'}})}});ui.resumePopup('panel');assert.equal(sim.s.speed,1);});
test('run speed cannot defeat a blocking panel',()=>{const {ui,sim}=fixture();ui.pauseForPopup('panel');ui.onClick({target:{closest:()=>({dataset:{a:'speed',v:'4'}})}});assert.equal(sim.s.speed,0);});
test('duplicate blockers retain safe 1x resume policy',()=>{const {ui,sim}=fixture(2);ui.pauseForPopup('panel');ui.pauseForPopup('panel');ui.resumePopup('panel');assert.equal(sim.s.speed,1);});
test('property change never applies stale previous-property run speed',()=>{const {ui}=fixture();ui.pauseForPopup('panel');const other=makeMaple(123);other.s.speed=0;ui.g.sim=other;ui.resumePopup('panel');assert.equal(other.s.speed,0);assert.equal(ui.popupBlocks.size,0);});
test('compact panels show concise metrics without performing management actions',()=>{const {ui,sim}=fixture();const before=JSON.stringify(sim.s);for(const title of ['Operate','Business','Growth','Customer feedback']){const h=ui.sheet(title,'', '<h3>Staff</h3><button>Existing action</button>');assert.match(h,/sheet compact/);assert.match(h,/dock-summary/);assert.match(h,/detail-content/);assert.match(h,/data-a="sheetGrow"/);assert.ok(h.indexOf('data-a="close"')<h.indexOf('class="body"'));}assert.equal(JSON.stringify(sim.s),before);});
test('expanded panel explicitly communicates pause and collapse',()=>{const {ui}=fixture();ui.sheetTall=true;const h=ui.sheet('Operate','', 'Retained action');assert.match(h,/sheet tall/);assert.match(h,/Paused/);assert.match(h,/Back to map/);assert.match(h,/Retained action/);});
test('inspector compact status uses authoritative occupied state',()=>{const {ui,sim}=fixture();const u=sim.objs('unit').find(u=>u.commercial==='occupied');ui.sel=u.id;assert.match(ui.dockSummary('Unit',''),/Occupied/);});
test('section navigation expands before jumping to controls',()=>{const {ui}=fixture();let expanded=false,jumped=false;ui.renderSheet=()=>{expanded=ui.sheetTall;};ui.jumpSection=()=>{assert.ok(expanded);jumped=true;};ui.onClick({target:{closest:()=>({dataset:{a:'section',v:'Staff'}})}});assert.ok(jumped);});
test('construction release pauses review; clearing preview resumes at 1x',()=>{const {ui,sim}=fixture(2),box={innerHTML:''};ui.$=()=>box;ui.tool='du10x10';ui.plan={status:'valid',cost:0,count:1,reasons:[],missing:[],dur:0};ui.buildPlacing=true;ui.renderActionBar();assert.equal(sim.s.speed,2);ui.finishPlacement();assert.equal(sim.s.speed,0);assert.match(box.innerHTML,/data-a="confirm"/);ui.plan=null;ui.renderActionBar();assert.equal(sim.s.speed,1);});
test('inbox preserves original response buttons without creating purchases',()=>{const {ui,sim}=fixture();const box={innerHTML:''};ui.$=()=>box;ui.requestCards=['<button data-a="convo" data-id="11" data-i="0">Existing choice $650</button>'];const cash=sim.s.cash;ui.showRequests();assert.match(box.innerHTML,/Existing choice \$650/);assert.match(box.innerHTML,/Close requests/);assert.equal(sim.s.cash,cash);assert.equal(sim.s.speed,0);});
test('expanded sheet pauses immediately and collapsing resumes at 1x',()=>{const {ui,sim}=fixture(4);const box={innerHTML:'',firstChild:null,querySelector(){return null;}};ui.$=()=>box;ui.syncFeedbackProperty=()=>{};ui.tab='business';ui.businessSheet=()=>ui.sheet('Business','', '<h3>Financing</h3>');ui.sheetTall=true;ui.renderSheet(true);assert.equal(sim.s.speed,0);ui.sheetTall=false;ui.renderSheet(true);assert.equal(sim.s.speed,1);});

test('commission actions stay outside collapsed details and are never duplicated',()=>{const {ui,sim}=fixture();const u=sim.objs('unit')[0];u.cstate='ready';u.order=987;ui.sel=u.id;const cash=sim.s.cash;const h=ui.inspector();const rail=h.slice(h.indexOf('class="dock-actions"'),h.indexOf('class="body"'));assert.match(rail,/Commission unit/);assert.match(rail,/Commission whole order/);assert.equal((h.match(/>Commission unit</g)||[]).length,1);assert.equal(sim.s.cash,cash);});
test('cleaning action stays available without expanding its information',()=>{const {ui}=fixture();ui.sel={kind:'dirt',f:0,x:10,y:10};const h=ui.inspector();const rail=h.slice(h.indexOf('class="dock-actions"'),h.indexOf('class="body"'));assert.match(rail,/Send Owner to clean/);});
test('tutorial clock instruction can dismiss tutorial details and start 1x',()=>{const {ui,sim}=fixture();ui.tutMin=false;ui.renderTut=()=>{};ui.pauseForPopup('tutorial');ui.onClick({target:{closest:()=>({dataset:{a:'speed',v:'1'}})}});assert.equal(ui.tutMin,true);assert.equal(sim.s.speed,1);assert.equal(ui.popupBlocks.size,0);});
test('tutorial clock action cannot bypass a pending customer request',()=>{const {ui,sim}=fixture();ui.renderTut=()=>{};ui.pauseForPopup('tutorial');ui.pauseForPopup('convo');ui.onClick({target:{closest:()=>({dataset:{a:'speed',v:'1'}})}});assert.equal(sim.s.speed,0);assert.equal(ui.popupBlocks.size,2);});

test('money lesson renders Got it in the compact completion row and advances',()=>{const {ui,sim}=fixture();sim.s.tut.beat=BEATS.findIndex(b=>b.id==='money');sim.s.tut.flags.businessOpened=true;ui.tutMin=true;ui.rend.setFocus=()=>{};ui.currentBlueprintPlan=()=>null;const box={innerHTML:''};ui.$=()=>box;ui.renderTut(true);assert.match(box.innerHTML,/class="tut min has-btn"/);assert.ok(box.innerHTML.indexOf('data-a="tutNext"')>box.innerHTML.indexOf('class="row tut-actions"'));ui.onClick({target:{closest:()=>({dataset:{a:'tutNext'}})}});assert.equal(sim.s.tut.flags.moneyAck,true);});
test('landscape overview retains left playfield with a right-side dock',()=>{const {ui}=fixture();globalThis.innerWidth=844;globalThis.innerHeight=390;const rect=(left,top,width,height)=>({left,top,width,height,right:left+width,bottom:top+height});ui.root={querySelector:()=>({getBoundingClientRect:()=>rect(8,8,300,96)})};ui.$=id=>id==='tabs'?{getBoundingClientRect:()=>rect(450,330,386,52)}:{firstElementChild:id==='sheet'?{getBoundingClientRect:()=>rect(456,140,380,180)}:null};const r=ui.safeRect();assert.equal(r.left,8);assert.equal(r.right,448);assert.ok(r.right-r.left>400);assert.equal(r.top,112);});
console.log(`${n} executed checks passed; physical Safari acceptance pending`);
