import assert from 'node:assert/strict';
import {unitStatus,UNIT_STATUS,loadingStatus} from '../../js/status.js';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {G} from '../../js/data.js';
import {UI} from '../../js/ui.js';
import {loadRenderer} from '../performance/renderer-fixture.mjs';
let n=0; const test=(name,fn)=>{fn();n++;console.log('PASS '+name)};
const sim=makeMaple(20261004); sim.ensure();
for(const [commercial,state] of Object.entries({ready:'available',occupied:'occupied',reserved:'reserved',unready:'turnover'})) test(commercial+' has its own cue',()=>assert.equal(unitStatus({cstate:'operating',commercial}),state));
test('blocked supersedes leased and ready status',()=>{for(const commercial of ['occupied','ready'])assert.equal(unitStatus({cstate:'operating',commercial,blocked:true}),'blocked')});
test('uncommissioned stock never appears available',()=>assert.equal(unitStatus({cstate:'ready',commercial:'ready'}),'commission'));
test('construction retains its state',()=>assert.equal(unitStatus({cstate:'construction',blocked:true}),'construction'));
test('all states have unique text and complementary colors',()=>{assert.equal(new Set(Object.values(UNIT_STATUS).map(x=>x.label)).size,7);assert.equal(new Set(Object.values(UNIT_STATUS).map(x=>x.color)).size,7)});
const i=sim.s.ground.findIndex((g,i)=>g===G.LOADING&&sim.D.vehReach[i]&&sim.D.walk[0][i]);assert.ok(i>=0);
const bay=()=>loadingStatus(sim).find(b=>b.i===i);sim.s.vehicles=[];
test('connected empty bay is free',()=>assert.equal(bay().state,'free'));
test('arriving vehicle claims bay before parking',()=>{sim.s.vehicles=[{dest:i,parked:null}];assert.equal(bay().state,'occupied')});
test('parked vehicle keeps its destination occupied',()=>{sim.s.vehicles[0].parked=i;assert.equal(bay().state,'occupied')});
test('departure frees bay',()=>{sim.s.vehicles[0].dest=null;sim.s.vehicles[0].parked=null;assert.equal(bay().state,'free')});
test('vehicle-disconnected bay is inaccessible even with a vehicle',()=>{sim.s.vehicles=[{dest:i}];sim.D.vehReach[i]=0;assert.equal(bay().state,'inaccessible');sim.D.vehReach[i]=1});
test('pedestrian-disconnected bay is inaccessible',()=>{const v=sim.D.walk[0][i];sim.D.walk[0][i]=0;assert.equal(bay().state,'inaccessible');sim.D.walk[0][i]=v});
test('status reads never mutate save state',()=>{const before=JSON.stringify(sim.s);loadingStatus(sim);sim.objs('unit').forEach(unitStatus);assert.equal(JSON.stringify(sim.s),before)});
test('property state does not leak between calls',()=>{const other=makeMaple(2);other.ensure();other.s.vehicles=[];assert.equal(loadingStatus(other).find(b=>b.i===i).state,'free');assert.equal(bay().state,'occupied')});
test('save resume derives same live bay and unit states',()=>{const resumed=new Sim(JSON.parse(JSON.stringify(sim.s)));resumed.ensure();assert.deepEqual(loadingStatus(resumed),loadingStatus(sim));assert.deepEqual(resumed.objs('unit').map(unitStatus),sim.objs('unit').map(unitStatus))});
const Renderer=await loadRenderer(), r=new Renderer({clientWidth:393,clientHeight:852},sim);r.rebuildStatic();
test('actual doors update all five cues without rebuilding',()=>{const a=r.anim.find(x=>x.k==='rollup');a.o.cstate='operating';a.o.blocked=false;const colors=[];for(const state of ['ready','occupied','reserved','unready']){a.o.commercial=state;r.updateAnim(.016,0);colors.push(a.mesh.material.color.getHex())}a.o.blocked=true;r.updateAnim(.016,0);colors.push(a.mesh.material.color.getHex());assert.equal(new Set(colors).size,5)});
test('selection differs from tutorial gold',()=>assert.equal(r.selMesh.material.color.getHex(),0x59d5ef));
test('badges retain shapes and hide upper units on ground view',()=>{const b=r.badges[0];b.o.f=1;b.o.cstate='operating';b.o.blocked=true;r.view=0;r.updateAnim(.016,0);assert.equal(b.sp.visible,false);r.view=1;r.updateAnim(.016,0);assert.equal(b.sp.visible,true);assert.equal(b.sp.material.map,r.tx.badges.missing)});
test('healthy occupied unit does not gain a floating badge',()=>{const b=r.badges[0];b.o.blocked=false;b.o.commercial='occupied';b.o.lease=null;r.updateAnim(.016,0);assert.equal(b.sp.visible,false)});
test('bay guidance names coordinates and distinguishes causes',()=>{const ui=Object.create(UI.prototype);ui.g={sim};const html=ui.statusLegendHtml();assert.ok(html.includes('Bay ('+i%sim.s.W+', '+Math.floor(i/sim.s.W)+')'));assert.match(html,/vehicle arriving/);assert.match(html,/hiring and canopies do not add bays/);assert.match(html,/route to a particular unit/)});
test('shared status materials survive scene rebuild and property cleanup',()=>{let disposed=0;for(const m of Object.values(r.statusMaterials))m.addEventListener('dispose',()=>disposed++);r.rebuildStatic();r.clearStatic();assert.equal(disposed,0)});
console.log(`${n} status/hierarchy checks passed`);
