import assert from 'node:assert/strict';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {tickVertical} from '../../js/vertical.js';
const clone=s=>new Sim(JSON.parse(JSON.stringify(s.s)));
let n=0;function test(name,fn){fn();console.log('PASS '+name);n++;}
function finish(sim,ord){for(let k=0;k<50000&&ord.st==='construction';k++){sim.s.t++;tickVertical(sim,ord);sim.ensure();for(const el of sim.objs('elevator'))sim.updateElevator(el);}assert.equal(ord.st,'done');}
function two(){const sim=makeMaple();sim.s.cash=1000000;sim.s.open=false;sim.s.opts={...sim.s.opts,competition:false};const sh=sim.objs('shell')[0],R=sim.verticalPlan(sh.id);assert.ok(R.ok,R.msg);assert.ok(sim.dispatch({type:'verticalUpgrade',...R}).ok);finish(sim,sim.s.orders.at(-1));sim.ensure();return sim;}
const base=two(),sh=base.objs('shell')[0],e=base.objs('elevator')[0];
test('legacy elevator at F2, priced F3 package, no mandatory stairs',()=>{assert.equal(sh.floors,2);assert.equal(e.dispatchMode,undefined);assert.equal(e.cap,4);const R=base.verticalPlan(sh.id);assert.ok(R.ok,R.msg);assert.equal(R.rows.find(r=>r.label==='Required freight landing extension').cost,1900);assert.equal(R.rows.find(r=>r.label==='F3 structure').cost,26*sh.w*sh.h);assert.equal(R.rows.find(r=>r.label==='Structural reinforcement').cost,4*sh.w*sh.h);assert.ok(!R.rows.some(r=>/stairs/i.test(r.label)));assert.equal(R.cost,R.rows.reduce((n,r)=>n+r.cost,0));assert.equal(base.verticalPlan(sh.id,{stairs:true}).ok,false);});
let full;
test('complete package charged exactly once; stale quote and duplicate refused',()=>{full=clone(base);const R=full.verticalPlan(sh.id),cash=full.s.cash;assert.ok(full.dispatch({type:'verticalUpgrade',...R}).ok);assert.equal(full.s.cash,cash-R.cost);assert.equal(full.dispatch({type:'verticalUpgrade',...R}).ok,false);assert.equal(full.s.cash,cash-R.cost);assert.equal(full.s.hall.length,3);assert.equal(full.s.objects[sh.id].floors,2);});
test('occupied legacy IDs/leases survive staged expansion; commissioning explicit',()=>{const before=base.objs('unit').map(u=>[u.id,u.num,u.lease]);finish(full,full.s.orders.at(-1));assert.equal(full.s.objects[sh.id].floors,3);assert.deepEqual(before,full.objs('unit').filter(u=>u.f!==2).map(u=>[u.id,u.num,u.lease]));const el=full.s.objects[e.id];assert.equal(el.dispatchMode,'sweep-v1');assert.deepEqual(el.servedFloors,[0,1,2]);const us=full.objs('unit').filter(u=>u.f===2);assert.ok(us.length);assert.ok(us.every(u=>!u.lease&&u.cstate!=='operating'));assert.ok(us.every(u=>u.cstate==='ready'),JSON.stringify(us.map(u=>u.missing)));assert.ok(full.dispatch({type:'commission',order:full.s.orders.at(-1).id}).ok);assert.ok(us.every(u=>u.cstate==='operating'&&u.commercial==='ready'));assert.equal(full.verticalPlan(sh.id).ok,false);});
test('deterministic construction reload with no second charge',()=>{const a=clone(base),R=a.verticalPlan(sh.id);a.dispatch({type:'verticalUpgrade',...R});let ord=a.s.orders.at(-1);for(let i=0;i<1400;i++){a.s.t++;tickVertical(a,ord);a.ensure();}const b=clone(a);finish(a,ord);finish(b,b.s.orders.at(-1));assert.deepEqual(a.s,b.s);});
function ag(sim,id,f,dest,cart=false){const el=sim.s.objects[e.id],a={id,kind:'cust',f,x:el.x+.5,y:el.y+.5,st:'toUnit',pi:0,exp:{elev:0,walk:0,door:0},cart:cart?id+100:null};sim.s.agents.push(a);if(cart)sim.s.carts.push({id:a.cart,st:'inuse',f,x:a.x,y:a.y,cond:1});sim.joinElevator(a,el,dest);return a;}
function drive(sim,predicate,limit=500){for(let i=0;i<limit&&!predicate();i++){sim.s.t++;for(const el of sim.objs('elevator'))sim.updateElevator(el);}assert.ok(predicate(),'elevator did not finish');}
test('cart/person slot capacity, mixed directions, eventual pickup and save midflight',()=>{const sim=clone(full);sim.s.agents=[];sim.s.carts=[];const el=sim.s.objects[e.id];Object.assign(el,{pos:0,tgt:null,door:0,q:[[],[],[]],riders:[]});const a=ag(sim,8000,0,2,true),b=ag(sim,8001,0,1,true),c=ag(sim,8002,0,2),d=ag(sim,8003,1,0);for(let i=0;i<8;i++){sim.s.t++;sim.updateElevator(el);assert.ok(el.riders.reduce((n,r)=>n+r.slots,0)<=4);}const copy=clone(sim);drive(sim,()=>[a,b,c,d].every(a=>!a.elev));drive(copy,()=>copy.s.agents.every(a=>!a.elev));assert.deepEqual(copy.s,sim.s);assert.equal(a.f,2);assert.equal(sim.cartById(a.cart).f,2);assert.equal(b.f,1);assert.equal(d.f,0);assert.equal(c.f,2);});
test('freight failure blocks F3 rental; cart cannot substitute stairs; repair retains riders',()=>{const sim=clone(full),el=sim.s.objects[e.id];sim.s.agents=[];const a=ag(sim,9000,0,2,true);drive(sim,()=>a.inElev);const pos=el.pos;el.cond=0;sim.markDirty();sim.ensure();for(let i=0;i<5;i++){sim.s.t++;sim.updateElevator(el);}assert.equal(el.pos,pos);assert.ok(a.inElev);assert.ok(sim.objs('unit').filter(u=>u.f===2).every(u=>u.blocked));el.cond=1;sim.markDirty();sim.ensure();drive(sim,()=>!a.elev);assert.equal(a.f,2);});
test('actual outbound/return cart path uses F3 elevator and ground wide door',()=>{const sim=clone(full);sim.s.agents=[];const el=sim.s.objects[e.id];Object.assign(el,{pos:0,tgt:null,door:0,q:[[],[],[]],riders:[]});const unit=sim.objs('unit').find(u=>u.f===2),front=sim.unitFront(unit)[0],cor=sim.objs('corral')[0];const a={id:10000,kind:'cust',st:'toUnit',f:0,x:cor.x+.5,y:cor.y+.5,exp:{elev:0,door:0,walk:0},cart:10001};sim.s.agents.push(a);sim.s.carts.push({id:a.cart,cond:1,st:'inuse',f:0,x:a.x,y:a.y});const trip=(f,x,y)=>{assert.ok(sim.goTo(a,f,x,y));let done=false;for(let i=0;i<700&&!done;i++){sim.s.t++;if(a.st!=='elev'){const r=sim.moveAgent(a,.2);done=r==='done';assert.notEqual(r,'blocked');}sim.updateElevator(el);}assert.ok(done);assert.equal(a.f,f);};trip(2,front.x,front.y);trip(0,cor.x,cor.y);assert.equal(sim.cartById(a.cart).f,0);});
test('cancellation does not strand a completed floor',()=>{const sim=clone(base),R=sim.verticalPlan(sh.id);sim.dispatch({type:'verticalUpgrade',...R});const ord=sim.s.orders.at(-1);const cash=sim.s.cash;assert.ok(sim.dispatch({type:'cancelOrder',id:ord.id}).ok);assert.equal(sim.s.cash,cash+R.cost);const fresh=sim.verticalPlan(sh.id);assert.ok(fresh.ok);sim.dispatch({type:'verticalUpgrade',...fresh});const q=sim.s.orders.at(-1);while(q.vertical.phase<2){sim.s.t++;tickVertical(sim,q);sim.ensure();}assert.equal(sim.dispatch({type:'cancelOrder',id:q.id}).ok,false);finish(sim,q);});
test('migration waits for an occupied legacy cab, retaining passenger and queue identities',()=>{const sim=clone(base),el=sim.s.objects[e.id];sim.s.agents=[];const R=sim.verticalPlan(sh.id);sim.dispatch({type:'verticalUpgrade',...R});const ord=sim.s.orders.at(-1);while(ord.vertical.phase<4){sim.s.t++;tickVertical(sim,ord);sim.ensure();}const a=ag(sim,12000,0,1,true);drive(sim,()=>a.inElev);const id=el.id,queues=el.q;sim.s.t++;tickVertical(sim,ord);assert.ok(ord.waiting);assert.equal(el.dispatchMode,undefined);assert.equal(el.id,id);assert.equal(el.q,queues);drive(sim,()=>!a.elev);finish(sim,ord);assert.equal(el.id,id);assert.equal(a.f,1);assert.equal(el.dispatchMode,'sweep-v1');assert.equal(el.q,queues);});
test('actual customer claims a cart, visits F3, returns cart and departs',()=>{const sim=clone(full);sim.s.agents=[];sim.s.carts=[];sim.s.vehicles=[];sim.rnd=()=>.01;const el=sim.s.objects[e.id];Object.assign(el,{pos:0,tgt:null,door:0,q:[[],[],[]],riders:[]});const u=sim.objs('unit').find(u=>u.f===2),cor=sim.objs('corral')[0],veh={id:13000,x:cor.x+.5,y:cor.y+1.5,path:[],pi:0};sim.s.vehicles.push(veh);sim.s.carts.push({id:13001,st:'corral',corral:cor.id,home:cor.id,cond:1,uses:0,f:0,x:cor.x,y:cor.y});const a={id:13002,kind:'cust',unit:u.id,veh:veh.id,vt:'bigaccess',st:'toCorral',f:0,x:cor.x+.5,y:cor.y+.5,corral:cor.id,needCart:true,exp:{elev:0,walk:0,door:0,cart:0,gate:0,office:0,dirt:0,dirtN:0},path:[],pi:0};sim.s.agents.push(a);let visited=false;for(let i=0;i<3000&&a.st!=='leave';i++){sim.s.t++;sim.updateCustomer(a);sim.updateElevator(el);if(a.st==='atunit'&&a.f===2)visited=true;}assert.ok(visited);assert.equal(a.st,'leave');assert.equal(sim.s.carts[0].st,'corral');assert.equal(sim.s.carts[0].f,0);assert.equal(a.cart,null);assert.equal(u.doorOpen,false);});
test('multiple working shafts choose congestion then ID and rebalance waiting freight after failure',()=>{const sim=clone(full),first=sim.s.objects[e.id],sh=sim.s.objects[base.objs('shell')[0].id];sim.s.agents=[];let cell;for(let y=sh.y;y<sh.y+sh.h&&!cell;y++)for(let x=sh.x;x<sh.x+sh.w;x++){const i=sim.idx(x,y);if(!sim.D.unitAt[2][i]&&!sim.D.roomAt[2][i]&&!sim.D.elevAt[i]&&sim.s.hall[2][i]===1){cell={x,y};break;}}assert.ok(cell);const second={...JSON.parse(JSON.stringify(first)),id:15000,...cell,pos:0,tgt:null,door:0,riders:[],q:[[],[],[]]};sim.s.objects[second.id]=second;sim.markDirty();sim.ensure();const u=sim.objs('unit').find(u=>u.f===2),fc=sim.unitFront(u)[0];const a={id:15001,kind:'cust',f:0,x:first.x+.5,y:first.y+.5,st:'walk',cart:15002,exp:{elev:0,walk:0,door:0}};sim.s.agents.push(a);assert.ok(sim.goTo(a,2,fc.x,fc.y));sim.joinElevator(a,first,2);const old=a.elevT0;first.cond=0;sim.markDirty();sim.ensure();sim.updateElevator(first);assert.equal(a.elev,null);assert.equal(a.elevQueuedAt,old);assert.ok(a.path.some(n=>sim.unnode(n).f===2&&sim.D.elevAt[n%(sim.s.W*sim.s.H)]===second.id));});
test('duplicate join preserves original waiting tick; stale callers do not survive',()=>{const sim=clone(full),el=sim.s.objects[e.id];sim.s.agents=[];Object.assign(el,{pos:0,tgt:null,door:0,riders:[],q:[[],[],[]]});const a=ag(sim,16000,0,2,true),t=a.elevT0;sim.s.t+=20;sim.joinElevator(a,el,2);assert.equal(a.elevT0,t);assert.deepEqual(el.q[0],[a.id]);el.q[1].push(999999);sim.updateElevator(el);assert.ok(!el.q.flat().includes(999999));});
console.log(`ALL PASS: ${n} three-floor gameplay checks`);
export {base,full};
