import assert from 'node:assert/strict';
import {UI} from '../../js/ui.js';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
const elem=()=>({innerHTML:'',classList:{add(){},remove(){},toggle(){}},querySelector(){return null}});
function fixture(){const u=Object.create(UI.prototype);u.g={sim:makeMaple(),audio:{play(){}}};u.g.sim.s.tut.on=false;u.g.sim.s.tut.done=true;u.g.sim.s.speed=0;u.g.rend={view:0,setView(v){this.view=v},setPreview(){},setOverlay(){},setSelection(){}};u.root={querySelector(){return null},querySelectorAll(){return []},classList:{add(){},remove(){},toggle(){}}};const els={};u.$=id=>els[id]||=elem();u.renderSheet=()=>{};u.renderActionBar=()=>{};u.syncFloorUi=()=>{};u.tool=null;u.title=false;u.toasts=[];u.bubbles=[];return u;}
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name)}
if(process.env.SST_REPRODUCE_37){const u=fixture();let removed=false;u.toasts=[{el:{remove(){removed=true}},text:'Promoted: old company'}];u.resetSession(0);assert.equal(removed,false);assert.equal(u.toasts.length,1);u.tool='du5x10';u.plan={args:{tool:'du5x10',a:{x:10,y:3},b:{x:10,y:3},f:0}};u.setTab('growth');assert.equal(u.tool,null);assert.equal(u.plan,null);assert.ok(u.growthPlanArgs);console.log('REPRODUCED 37: stale toast and cleared construction preview');process.exit(0);}
test('load/switch reset removes old messages and stale proposal without mutating save',()=>{const u=fixture(),before=JSON.stringify(u.sim.s);let removed=0;u.toasts=[{el:{remove(){removed++}}}];u.growthProposal={sim:u.sim,args:{}};u.growthPlanArgs={tool:'du5x10'};u.resetSession(0);assert.equal(removed,1);assert.equal(u.toasts.length,0);assert.equal(u.growthProposal,null);assert.equal(u.growthPlanArgs,null);assert.equal(JSON.stringify(u.sim.s),before);});
test('Growth review restores exact proposal options without buying or unpausing',()=>{const u=fixture();u.sim.s.cash=1e6;u.sim.s.coTier=2;u.pickTool('du5x10');u.flip=true;u.climate=true;u.rush=true;u.placeStart({x:10,y:3});const args=structuredClone(u.plan.args),before=JSON.stringify(u.sim.s);u.setTab('growth');assert.equal(u.tool,null);assert.deepEqual(u.growthPlanArgs,args);assert.equal(u.growthProposal.sim,u.sim);assert.equal(JSON.stringify(u.sim.s),before);u.returnGrowthProposal();assert.deepEqual(u.plan.args,args);assert.equal(u.sim.s.speed,0);assert.equal(JSON.stringify(u.sim.s),before);});
test('review cannot restore another property proposal',()=>{const u=fixture();u.growthProposal={sim:makeMaple(),args:{tool:'du5x10'}};assert.equal(u.returnGrowthProposal(),false);assert.equal(u.tool,null);});
test('choosing a different tool discards reviewed proposal',()=>{const u=fixture();u.pickTool('du5x10');u.placeStart({x:10,y:3});u.setTab('growth');u.pickTool('du10x10');assert.equal(u.growthProposal,null);assert.equal(u.growthPlanArgs,null);});
test('production fixture 06 returns to valid $620 plan then normal debit',()=>{const path=process.env.SST_FIXTURE_06;assert.ok(path,'set SST_FIXTURE_06');const code=readFileSync(path,'utf8').trim();const saved=JSON.parse(gunzipSync(Buffer.from(code.slice(5),'base64')));const u=fixture();u.g.sim=new Sim(saved.company?saved.props[saved.active].s:saved);u.pickTool('du5x10');u.placeStart({x:10,y:3});u.finishPlacement();assert.equal(u.plan.cost,620);assert.equal(u.plan.status,'valid');assert.ok(u.sim.growthReadiness(u.plan).justified);const cash=u.sim.s.cash;u.setTab('growth');u.returnGrowthProposal();assert.equal(u.plan.cost,620);assert.equal(u.sim.s.cash,cash);u.toast=()=>{};u.confirmPlan();assert.equal(u.sim.s.cash,cash-620);assert.equal(u.growthProposal,null);assert.equal(u.growthPlanArgs,null);});
test('return requotes a proposal against changed map conditions',()=>{const u=fixture();u.sim.s.cash=1e6;u.pickTool('du5x10');u.placeStart({x:10,y:3});u.setTab('growth');let calls=0;const original=u.sim.plan.bind(u.sim);u.sim.plan=args=>{calls++;return original(args)};u.returnGrowthProposal();assert.ok(calls>0);});
console.log(n+' UI regression groups passed');
