import assert from 'node:assert/strict';
import {loadRenderer} from '../performance/renderer-fixture.mjs';
import {makeMaple} from '../../js/maple.js';
import {Sim} from '../../js/sim.js';
import {UI} from '../../js/ui.js';
const Renderer=await loadRenderer();const sim=makeMaple(31),r=new Renderer({clientWidth:393,clientHeight:720},sim);sim.s.speed=4;let n=0;const test=(name,f)=>{f();console.log('PASS '+name);n++;};
test('architecture batches cover built units without per-part draws or simulation mutations',()=>{const saved=JSON.stringify(sim.s);r.rebuildStatic();const batches=r.staticG.children.filter(m=>m.userData.decoration==='frame'||m.userData.decoration==='eave');assert.ok(batches.length>0&&batches.length<=6);assert.ok(batches.every(m=>m.isInstancedMesh&&!m.castShadow));const frames=batches.filter(m=>m.userData.decoration==='frame').reduce((n,m)=>n+m.count,0);assert.equal(frames,sim.objs('unit').filter(u=>u.cstate!=='construction').length*3);assert.equal(JSON.stringify(sim.s),saved);});
test('batched trim follows actual selected floor',()=>{const batch=r.staticG.children.find(m=>m.userData.decoration==='frame');batch.userData.f=1;r.setView(0);assert.equal(batch.visible,false);r.setView(1);assert.equal(batch.visible,true);r.setView('ext');assert.equal(batch.visible,true);});
test('instance GPU resources are disposed on rebuild, shared geometry survives',()=>{const batch=r.staticG.children.find(m=>m.isInstancedMesh);let disposed=0,geometry=0;batch.addEventListener('dispose',()=>disposed++);r.geo.box.addEventListener('dispose',()=>geometry++);r.rebuildStatic();assert.equal(disposed,1);assert.equal(geometry,0);});
test('individual wheels exist on all five vehicle types',()=>{for(const type of ['sedan','suv','pickup','van','box']){const m=r.vehMesh({type,color:'#668899'});assert.equal(m.userData.wheels.length,4);for(const w of m.userData.wheels){assert.equal(w.children.length,2);assert.ok(w.children.every(c=>!c.castShadow));}r.disposeTree(m);}});
test('wheel rotation follows real rendered travel and stops at manual pause',()=>{sim.s.vehicles=[{id:999,type:'sedan',color:'#668899',x:3,y:3}];r.updateDynamic(.016);const m=r.pool.veh.get(999);sim.s.vehicles[0].x+=.1;r.updateDynamic(.016);assert.ok(m.userData.wheelPhase>0);sim.s.speed=0;const phase=m.userData.wheelPhase;r.updateDynamic(.016);assert.equal(m.userData.wheelPhase,phase);sim.s.speed=4;});
test('separate legs stride oppositely; carrying remains driven by carry state',()=>{const a={id:888,kind:'cust',st:'walk'},m=r.personMesh(a);r.posePerson(m,a,.02,1);assert.equal(m.userData.strides.length,2);assert.equal(m.userData.strides[0].rotation.z,-m.userData.strides[1].rotation.z);r.posePerson(m,{...a,st:'atunit',carry:true},0,1);assert.ok(m.userData.arms[0].rotation.z<-.9);assert.equal(m.userData.strides[0].rotation.z,0);});
test('recycled people reset strides and retained private resources dispose once',()=>{const a={id:888,kind:'cust'},m=r.personMesh(a);r.posePerson(m,a,.03,1);r.customerFree.push(m);const reuse=r.personMesh({...a,id:889});assert.equal(reuse,m);assert.equal(m.userData.strides[0].rotation.z,0);let disposed=0;m.userData.strides[0].children[0].material.addEventListener('dispose',()=>disposed++);r.disposeTree(m);assert.equal(disposed,1);});
test('rendering a running simulation retains exact state and RNG parity',()=>{const a=makeMaple(31),b=new Sim(JSON.parse(JSON.stringify(a.s)));const view=new Renderer({clientWidth:393,clientHeight:720},a);for(let i=0;i<300;i++){a.step();b.step();a.ensure();b.ensure();if(i%20===0)view.rebuildStatic();view.time+=.016;view.updateDynamic(.016);view.updateSky(.016);view.updateAnim(.016);}assert.deepEqual(a.s,b.s);});
const original=document.createElement;document.createElement=t=>t==='span'?{textContent:'',dataset:{},style:{},hidden:false,setAttribute(k,v){this[k]=v;}}:original(t);globalThis.innerWidth=1000;globalThis.innerHeight=800;
function labels(selected,overlap=false){const units=[1,2,3].map((id,i)=>({id,type:'unit',num:100+id,x:i,y:1,w:1,h:1,f:0,dir:[0,1],access:'drive',cstate:'operating',commercial:'occupied',blocked:id===3}));const ui=Object.create(UI.prototype);ui.sel=selected;const root={appendChild(){}};ui.$=()=>root;ui.g={sim:{s:{objects:Object.fromEntries(units.map(o=>[o.id,o]))}},rend:{canvas:{clientHeight:800},frustum:30,zoom:2,view:0,project:(x,y)=>({x:overlap?100:x*250+50,y:200,vis:true})}};ui.updateLabels([]);return ui.lblPool;}
test('routine occupied labels are compact; selection and exceptions stay explicit',()=>{const l=labels(2);assert.ok(l.some(e=>e.textContent==='101'));assert.ok(l.some(e=>e.textContent==='102 · Occupied'));assert.ok(l.some(e=>e.textContent==='103 · Blocked'));assert.equal(l.find(e=>e.textContent==='101')['aria-label'],'Unit 101: Occupied');});
test('selected label wins collision budget over routine labels',()=>{const l=labels(2,true);assert.equal(l.filter(e=>!e.hidden).length,1);assert.equal(l[0].textContent,'102 · Occupied');});
console.log(`${n} second visual pass checks passed`);
